// INTERFACE/MODEL only. No real SDK, trusted date or player Storage proof.
import test from 'node:test';import assert from 'node:assert/strict';
import {SourceAutoUpgradeAdClient} from '../auto-upgrade-ad-client';import {sourceAutoAdReward,sourceAutoAdRequestGate} from '../r6-auto-upgrade-ad';
import {freshSourceMetaState,decodeSourceMetaState,serializeSourceMetaState,runtimeSourceAutoUpgradeTick} from '../source-meta-runtime';
import {createSession,serializeSession,deserializeSession} from '../session';import {createActivityState} from '../source-activities';import {freshPlatformState,decodePlatformState} from '../local-platform';
import {createSourceLocalRewardProvider} from '../r6-reward-ad-policy';import {sourceAutoUpgradeEnabled} from '../r5-auto';import {walletValue} from '../rules';
const resp=(q,status='success')=>({...q,status,provider:'local-test',onlineVerified:false});
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve};};
function fixture(opts={}){
 const c={ctx:'A',day:'h5-local:2026-10-04',writes:0,fail:false,requests:[],notes:[],shown:0,b:{session:createSession(),activities:createActivityState(),platform:freshPlatformState(),meta:freshSourceMetaState()}};
 c.owner=new SourceAutoUpgradeAdClient({read:()=>({bundle:c.b,contextID:c.ctx}),write:b=>{if(c.fail)throw Error('quota');c.writes++;c.b=b;},todayKey:()=>c.day,requestID:()=>`A${c.requests.length}`,execute:async q=>{c.requests.push(q);return opts.execute?opts.execute(q):resp(q,opts.status);},notice:n=>c.notes.push(n),granted:()=>{c.shown++;}});return c;
}
test('type12 success persists date/600 then reports local-test',async()=>{const c=fixture();assert(await c.owner.request());assert.equal(c.requests[0].adType,12);assert.equal(c.requests[0].purpose,'auto-upgrade:12');assert.equal(c.b.meta.autoUpgrade.adRemainingSec,600);assert.equal(c.b.meta.autoUpgrade.lastAdDate,c.day);assert.equal(c.b.platform.sequence,1);assert.equal(c.writes,1);assert.equal(c.shown,1);assert.equal(c.owner.adShowing,false);assert.match(c.notes.at(-1),/本地测试.*线上未连接/);});
for(const status of ['failure','cancelled','unavailable'])test(`type12 ${status} no date/time/receipt mutation`,async()=>{const c=fixture({status}),b=c.b;assert(!await c.owner.request());assert.equal(c.b,b);assert.equal(c.writes,0);assert.equal(c.owner.pending,null);assert.equal(c.owner.adShowing,false);});
for(const [label,change,pattern] of [['permanent',c=>c.b.meta.entitlements.autoUpgradePack=true,/永久/],['active',c=>c.b.meta.autoUpgrade.adRemainingSec=1,/生效/],['used',c=>c.b.meta.autoUpgrade.lastAdDate=c.day,/今日/],['backward',c=>c.b.meta.autoUpgrade.lastAdDate='h5-local:2026-10-05',/倒退/],['mode',c=>c.b.session.mode='mine',/普通/],['date',c=>c.day='',/日期/]])test(`type12 admission ${label} without provider`,async()=>{const c=fixture();change(c);assert(!await c.owner.request());assert.equal(c.requests.length,0);assert.match(c.notes.at(-1),pattern);});
test('success callback has no admission permanent/active/day/switch gate',()=>{const c=fixture();c.b.meta.entitlements.autoUpgradePack=true;c.b.meta.autoUpgrade={requested:false,lastAdDate:c.day,adRemainingSec:200};const r=sourceAutoAdReward(c.b,c.day,'R');assert.equal(r.status,'granted');assert.equal(r.bundle.meta.autoUpgrade.adRemainingSec,600);assert.equal(r.bundle.meta.autoUpgrade.requested,false);assert.equal(r.bundle.meta.entitlements.autoUpgradePack,true);});
test('immediate source AutoUpgrade_All consumes affordable wallet at callback even when a panel is open',async()=>{const c=fixture();c.b.session.battle={...c.b.session.battle,coins:10000,coinsValue:undefined};assert(await c.owner.request());assert(Object.values(c.b.session.battle.upgradeLevels).some(n=>n>0));assert(walletValue(c.b.session.battle).lt(10000));assert(c.b.session.events.some(e=>e.type==='upgradeSucceeded'));});
test('disabled switch stores time without auto purchases and native time still decreases',async()=>{const c=fixture();c.b.meta.autoUpgrade.requested=false;c.b.session.battle={...c.b.session.battle,coins:10000,coinsValue:undefined};assert(await c.owner.request());assert.equal(walletValue(c.b.session.battle).toNumber(),10000);assert(!sourceAutoUpgradeEnabled(c.b.meta.autoUpgrade,false));c.b=runtimeSourceAutoUpgradeTick(c.b,1,false);assert.equal(c.b.meta.autoUpgrade.adRemainingSec,599.5);});
test('permanent pack or any ad showing pauses native timer; expiry clamped and reload never adds offline credit',async()=>{const c=fixture();assert(await c.owner.request());const before=c.b;assert.equal(runtimeSourceAutoUpgradeTick(c.b,1,true),before);c.b.meta.entitlements.autoUpgradePack=true;assert.equal(runtimeSourceAutoUpgradeTick(c.b,1),c.b);c.b.meta.entitlements.autoUpgradePack=false;c.b.meta.autoUpgrade.adRemainingSec=.1;c.b=runtimeSourceAutoUpgradeTick(c.b,5);assert.equal(c.b.meta.autoUpgrade.adRemainingSec,0);assert.equal(decodeSourceMetaState(serializeSourceMetaState(c.b.meta)).autoUpgrade.adRemainingSec,0);});
test('provider pending tracks adShowing; double request executes once',async()=>{const d=deferred(),c=fixture({execute:()=>d.promise}),a=c.owner.request();assert(c.owner.adShowing);assert(!await c.owner.request());assert.equal(c.requests.length,1);d.resolve(resp(c.requests[0]));assert(await a);assert.equal(c.b.platform.sequence,1);assert(!c.owner.adShowing);});
test('save failure unpublished and stops adShowing; retry merges current state without another ad',async()=>{const c=fixture();c.fail=true;assert(!await c.owner.request());assert.equal(c.b.meta.autoUpgrade.adRemainingSec,0);assert.equal(c.b.platform.sequence,0);assert(c.owner.saveFailed);assert(!c.owner.adShowing);c.b.session={...c.b.session,diamonds:777};c.b.meta.autoUpgrade.requested=false;c.day='h5-local:2026-10-05';c.fail=false;assert(c.owner.retrySave());assert.equal(c.b.session.diamonds,777);assert.equal(c.b.meta.autoUpgrade.lastAdDate,c.day);assert.equal(c.b.meta.autoUpgrade.requested,false);assert.equal(c.requests.length,1);assert.equal(c.writes,1);assert(!c.owner.retrySave());});
test('late manager callback crosses midnight and preserves current toggle/permanent unrelated wallets',async()=>{const d=deferred(),c=fixture({execute:()=>d.promise}),a=c.owner.request();c.day='h5-local:2026-10-05';c.b.meta.autoUpgrade.requested=false;c.b.meta.entitlements.autoUpgradePack=true;c.b.session.diamonds=777;d.resolve(resp(c.requests[0]));assert(await a);assert.equal(c.b.meta.autoUpgrade.lastAdDate,c.day);assert.equal(c.b.meta.autoUpgrade.adRemainingSec,600);assert.equal(c.b.meta.autoUpgrade.requested,false);assert.equal(c.b.session.diamonds,777);});
test('different save context discards callback',async()=>{const d=deferred(),c=fixture({execute:()=>d.promise}),a=c.owner.request();c.ctx='B';d.resolve(resp(c.requests[0]));assert(!await a);assert.equal(c.writes,0);assert.equal(c.owner.pending,null);assert(!c.owner.adShowing);});
test('invalidate old request does not clear a new request adShowing',async()=>{const d=deferred(),e=deferred(),c=fixture({execute:q=>q.id==='A0'?d.promise:e.promise}),a=c.owner.request();c.owner.invalidate();const b=c.owner.request();d.resolve(resp(c.requests[0]));assert(!await a);assert(c.owner.adShowing);e.resolve(resp(c.requests[1]));assert(await b);assert.equal(c.writes,1);});
for(const field of ['id','purpose','kind','provider','onlineVerified'])test(`type12 mismatched ${field} callback never grants`,async()=>{const c=fixture({execute:q=>({...resp(q),[field]:field==='onlineVerified'?true:'wrong'})});assert(!await c.owner.request());assert.equal(c.writes,0);});
test('throwing provider clears busy and does not grant',async()=>{const c=fixture({execute:()=>{throw Error('oops');}});assert(!await c.owner.request());assert(!c.owner.adShowing);assert.equal(c.owner.pending,null);assert.equal(c.writes,0);});
test('codec preserves timer/day/receipt, repeat same callback blocked; native same-day new callback replaces not adds',async()=>{const c=fixture();assert(await c.owner.request());c.b={...c.b,session:deserializeSession(serializeSession(c.b.session)),meta:decodeSourceMetaState(serializeSourceMetaState(c.b.meta)),platform:decodePlatformState(JSON.stringify(c.b.platform))};assert.equal(c.b.meta.autoUpgrade.adRemainingSec,600);assert.equal(sourceAutoAdReward(c.b,c.day,'A0').status,'blocked');c.b.meta.autoUpgrade.adRemainingSec=10;assert.equal(sourceAutoAdReward(c.b,c.day,'another').bundle.meta.autoUpgrade.adRemainingSec,600);});
for(const right of ['removeAdsAll','adRemoved','removeAdsForced'])test(`type12 ${right} reward SDK bypass matches source`,async()=>{const c=fixture();c.b.meta.entitlements[right]=true;const provider=createSourceLocalRewardProvider(c.b.meta.entitlements,false,'failure');const out=await provider.execute({id:right,purpose:'auto-upgrade:12',kind:'ad'});assert.equal(out.status,right==='removeAdsForced'?'unavailable':'success');assert.equal(out.onlineVerified,false);});
test('invalid IDs and callback local clock rollback blocked, no state mutation',()=>{const c=fixture();for(const id of ['','x'.repeat(129)])assert.equal(sourceAutoAdReward(c.b,c.day,id).status,'blocked');c.b.meta.autoUpgrade.lastAdDate='h5-local:2026-10-05';assert.equal(sourceAutoAdReward(c.b,c.day,'A').status,'blocked');assert.equal(sourceAutoAdRequestGate(c.b,c.day),'本地日期倒退；未再次发放增益');});
import {sourceAutoAdPanelProjection} from '../r6-auto-upgrade-ad';
test('source Reload shows daily exhausted Shop not ad; permanent hides both timer and purchase popup',()=>{const c=fixture();assert.deepEqual(sourceAutoAdPanelProjection(c.b.meta.autoUpgrade,false,c.day),{nonPurchase:true,purchase:false,shop:false,ad:true,on:false,off:false,time:false,inApp:true});c.b.meta.autoUpgrade.lastAdDate=c.day;const used=sourceAutoAdPanelProjection(c.b.meta.autoUpgrade,false,c.day);assert(used.shop);assert(!used.ad);const perm=sourceAutoAdPanelProjection(c.b.meta.autoUpgrade,true,c.day);assert(perm.purchase);assert(perm.on);assert(!perm.time);assert(!perm.inApp);c.b.meta.autoUpgrade.requested=false;c.b.meta.autoUpgrade.adRemainingSec=300;const off=sourceAutoAdPanelProjection(c.b.meta.autoUpgrade,false,c.day);assert(off.off);assert(off.time);assert(!off.ad);});
