// INTERFACE/MODEL; no natural player Storage, real ad, trusted date or native RNG parity.
import test from 'node:test';import assert from 'node:assert/strict';
import {SourceGunDailyClient} from '../gun-daily-client';
import {sourceGunDailyReward,sourceGunDailyRequestGate} from '../r6-gun-daily';
import {createSourceLocalRewardProvider} from '../r6-reward-ad-policy';
import {freshSourceMetaState,decodeSourceMetaState,serializeSourceMetaState} from '../source-meta-runtime';
import {createSession,sourceGun,serializeSession,deserializeSession} from '../session';
import {createActivityState} from '../source-activities';import {freshPlatformState,decodePlatformState} from '../local-platform';
const response=(q,status='success')=>({...q,status,provider:'local-test',onlineVerified:false});
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve};};
function fixture(options={}){
 const c={ctx:'A',day:'h5-local:2026-10-04',writes:0,fail:false,notes:[],requests:[],presented:[],b:{session:{...createSession(),mode:'field',historicMax:30,gunInventory:[{...sourceGun(0),uid:'owned-0'}],diamonds:321},activities:createActivityState(),platform:freshPlatformState(),meta:freshSourceMetaState()}};
 c.b.meta.adDailyGun.serverWeapon01AdOn=true;
 c.owner=new SourceGunDailyClient({read:()=>({bundle:c.b,contextID:c.ctx}),write:b=>{if(c.fail)throw Error('save');c.b=b;c.writes++;},todayKey:()=>c.day,requestID:()=>`daily-${c.requests.length}`,execute:q=>{c.requests.push(q);return options.execute?options.execute(q):Promise.resolve(response(q,options.outcome??'success'));},notice:n=>c.notes.push(n),granted:(gun,slot)=>{c.presented.push({gun,slot});if(options.presentationFailure)throw Error('presentation');}});return c;
}
test('type10 persists stable gun5..9, catalog/date/RNG/receipt and no diamond charge once',async()=>{
 const c=fixture(),rng=c.b.session.rngState;assert(await c.owner.request());assert.equal(c.requests[0].adType,10);assert.equal(c.requests[0].purpose,'gun:daily:10');
 assert.equal(c.b.session.gunInventory.length,2);const g=c.b.session.gunInventory[1];assert.match(g.uid,/daily:daily-0/);assert(c.b.session.catalogSeen.includes(Number(g.id.split('-').at(-1))));assert.equal(c.b.session.diamonds,321);assert.notEqual(c.b.session.rngState,rng);assert.equal(c.b.session.gunDraws,1);assert.equal(c.b.meta.adDailyGun.lastDailyGunKey,c.day);assert.equal(c.b.platform.sequence,1);assert.equal(c.b.platform.claims.length,1);assert.equal(c.presented.length,1);assert(!await c.owner.request());assert.equal(c.requests.length,1);
});
for(const status of ['failure','cancelled','unavailable'])test(`${status} consumes neither gun/day/RNG nor receipt`,async()=>{const c=fixture({outcome:status}),before=c.b;assert(!await c.owner.request());assert.equal(c.b,before);assert.equal(c.writes,0);assert.equal(c.presented.length,0);assert.equal(c.owner.pending,null);});
for(const changed of [{id:'wrong'},{purpose:'wrong'},{kind:'purchase'},{provider:'online'},{onlineVerified:true}])test(`mismatched callback ${JSON.stringify(changed)} rejected`,async()=>{const c=fixture({execute:q=>Promise.resolve({...response(q),...changed})});assert(!await c.owner.request());assert.equal(c.writes,0);});
for(const [name,mutate] of [
 ['progress',c=>c.b.session.historicMax=29],['server',c=>c.b.meta.adDailyGun.serverWeapon01AdOn=false],['mode',c=>c.b.session.mode='challenge'],['full',c=>c.b.session.gunInventory=Array.from({length:16},(_,i)=>sourceGun(i))],['used',c=>c.b.meta.adDailyGun.lastDailyGunKey=c.day],['invalid-date',c=>c.day='h5-local:2026-02-30'],['backward-date',c=>c.b.meta.adDailyGun.lastDailyGunKey='h5-local:2026-10-05'],['old-receipt',c=>c.b.platform.claims=[`meta:developer-ad-daily-gun:${c.day}`]]
])test(`request ${name} gate prevents provider and mutation`,async()=>{const c=fixture();mutate(c);assert(!await c.owner.request());assert.equal(c.requests.length,0);assert.equal(c.writes,0);});
test('save failure retry publishes nothing before write and does not repeat provider',async()=>{const c=fixture(),before=c.b;c.fail=true;assert(!await c.owner.request());assert.equal(c.b,before);assert(c.owner.saveFailed);assert(!await c.owner.request());assert.equal(c.requests.length,1);assert.equal(c.presented.length,0);c.fail=false;assert(c.owner.retrySave());assert.equal(c.requests.length,1);assert.equal(c.writes,1);assert.equal(c.presented.length,1);assert(!c.owner.retrySave());});
test('failed save retry rechecks date and merges current wallet/inventory',async()=>{const c=fixture();c.fail=true;assert(!await c.owner.request());c.day='h5-local:2026-10-05';c.b={...c.b,session:{...c.b.session,diamonds:456,gunInventory:[...c.b.session.gunInventory,{...sourceGun(8),uid:'concurrent'}]}};c.fail=false;assert(c.owner.retrySave());assert.equal(c.b.meta.adDailyGun.lastDailyGunKey,c.day);assert.equal(c.b.session.diamonds,456);assert.equal(c.b.session.gunInventory[2].uid,'daily:daily-0');});
test('full inventory at callback consumes nothing and does not advance RNG',async()=>{const d=deferred(),c=fixture({execute:()=>d.promise});const p=c.owner.request();c.b.session.gunInventory=Array.from({length:16},(_,i)=>sourceGun(i));const rng=c.b.session.rngState;d.resolve(response(c.requests[0]));assert(!await p);assert.equal(c.b.session.rngState,rng);assert.equal(c.b.meta.adDailyGun.lastDailyGunKey,null);assert.equal(c.writes,0);});
test('source callback uses current date even after panel close and server/progress changes',async()=>{const d=deferred(),c=fixture({execute:()=>d.promise});const p=c.owner.request();c.day='h5-local:2026-10-05';c.b.meta.adDailyGun.serverWeapon01AdOn=false;c.b.session.historicMax=0;c.b.session.overlay='none';d.resolve(response(c.requests[0]));assert(await p);assert.equal(c.b.meta.adDailyGun.lastDailyGunKey,c.day);assert.equal(c.b.meta.adDailyGun.serverWeapon01AdOn,false);});
test('context replacement and invalidate discard delayed callbacks',async()=>{for(const invalidate of [false,true]){const d=deferred(),c=fixture({execute:()=>d.promise});const p=c.owner.request();if(invalidate)c.owner.invalidate();else c.ctx='B';d.resolve(response(c.requests[0]));assert(!await p);assert.equal(c.writes,0);assert.equal(c.owner.pending,null);}});
test('provider throws clear pending without granting; successful presentation throw cannot revoke reward',async()=>{const c=fixture({execute:()=>Promise.reject(Error('sdk'))});assert(!await c.owner.request());assert.equal(c.owner.pending,null);assert.equal(c.writes,0);const other=fixture({presentationFailure:true});assert(await other.owner.request());assert.equal(other.writes,1);assert(!await other.owner.request());});
test('two requests serialize; duplicate receipt fails closed regardless of date',async()=>{const d=deferred(),c=fixture({execute:()=>d.promise});const p=c.owner.request();assert(!await c.owner.request());d.resolve(response(c.requests[0]));assert(await p);c.day='h5-local:2026-10-05';assert.equal(sourceGunDailyReward(c.b,c.day,'daily-0').status,'duplicate');assert.equal(c.writes,1);});
test('old and new save codecs preserve gun UID/day/claims without grants',async()=>{const c=fixture();assert(await c.owner.request());const session=deserializeSession(serializeSession(c.b.session)),meta=decodeSourceMetaState(serializeSourceMetaState(c.b.meta)),platform=decodePlatformState(JSON.stringify(c.b.platform));assert.equal(session.gunInventory[1].uid,c.b.session.gunInventory[1].uid);assert.equal(meta.adDailyGun.lastDailyGunKey,c.day);assert.equal(platform.claims[0],c.b.platform.claims[0]);assert.match(sourceGunDailyRequestGate({...c.b,session,meta,platform},c.day),/已领取/);});
for(const key of ['removeAdsAll','adRemoved'])test(`${key} bypasses unavailable rewarded SDK but not purchase`,async()=>{const c=fixture();c.b.meta.entitlements[key]=true;const provider=createSourceLocalRewardProvider(c.b.meta.entitlements,false,'failure'),ad={id:'ad',purpose:'type10',kind:'ad'};assert.equal((await provider.execute(ad)).status,'success');assert.equal((await provider.execute({id:'buy',purpose:'pack',kind:'purchase'})).status,'unavailable');});
test('only forced removal is insufficient; reward bypass still preserves daily gate',async()=>{const c=fixture();c.b.meta.entitlements.removeAdsForced=true;assert.equal((await createSourceLocalRewardProvider(c.b.meta.entitlements,false).execute({id:'ad',purpose:'type10',kind:'ad'})).status,'unavailable');c.b.meta.entitlements.removeAdsAll=true;c.b.meta.adDailyGun.lastDailyGunKey=c.day;assert(!await c.owner.request());assert.equal(c.requests.length,0);});
test('rights provider deduplicates across both branches and rejects conflicting request identity',async()=>{const c=fixture();c.b.meta.entitlements.removeAdsAll=true;const p=createSourceLocalRewardProvider(c.b.meta.entitlements,false),q={id:'A',purpose:'gun',kind:'ad'};assert.equal(p.execute(q),p.execute({...q}));assert.throws(()=>p.execute({...q,kind:'purchase'}),/identity conflict/);const r=await p.execute(q);assert.equal(r.provider,'local-test');assert.equal(r.onlineVerified,false);});
