// STATIC + MODEL/INTERFACE; isolated fixtures, no source-device or online proof.
import test from 'node:test';import assert from 'node:assert/strict';
import {SOURCE_OFFERWALL,freshSourceOfferWall,decodeSourceOfferWall,createLocalOfferWallProvider,sourceOfferWallDebit,sourceOfferWallGrant,sourceOfferWallExposure} from '../r6-offerwall';
import {SourceOfferWallClient} from '../offerwall-client';
import {freshSourceMetaState,serializeSourceMetaState,decodeSourceMetaState} from '../source-meta-runtime';
import {SOURCE_QA_SCENARIOS,createSourceQAStorage} from '../r6-qa';
function harness(){
 const c={state:freshSourceOfferWall(),diamonds:500,contextID:'A',saveLoaded:true,now:0,writes:[],requests:[],notes:[],fail:()=>false,outcome:'success',available:true,contentReady:true};
 const provider=createLocalOfferWallProvider({available:true,read:()=>c.state,debit:q=>c.write(sourceOfferWallDebit(c.state,q),c.diamonds)});
 c.execute=q=>provider.execute(q);c.write=(s,d)=>{if(c.fail(s,d))throw Error('quota');c.state=s;c.diamonds=d;c.writes.push({state:JSON.parse(JSON.stringify(s)),diamonds:d});};
 let sequence=0;c.owner=new SourceOfferWallClient({read:()=>c,write:c.write,execute(q,ctx){c.requests.push({...q,contextID:ctx});return c.execute(q);},requestID:()=>`local:${sequence++}`,now:()=>c.now,notice:n=>c.notes.push(n)});return c;
}
const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
test('source literals/time consumers are explicit, default balances zero',()=>{assert.equal(SOURCE_OFFERWALL.placement,'offerwall_aos');assert.equal(SOURCE_OFFERWALL.pendingKey,'ow_pending_gem');assert.equal(SOURCE_OFFERWALL.claimTimeoutSec,20);assert.equal(SOURCE_OFFERWALL.dismissDelaySec,3.5);assert.equal(SOURCE_OFFERWALL.resumeDelaySec,5);assert.equal(freshSourceOfferWall().localBalance,0);});
test('legacy metadata migration defaults zero and rejects malformed ledgers',()=>{const m=freshSourceMetaState();delete m.offerWall;const loaded=decodeSourceMetaState(serializeSourceMetaState(m));assert.deepEqual(loaded.offerWall,freshSourceOfferWall());assert(!loaded.entitlements.adRemoved);for(const s of [null,{}, {...freshSourceOfferWall(),localBalance:-1},{...freshSourceOfferWall(),localBalance:1.5},{...freshSourceOfferWall(),localGrants:['fake']},{...freshSourceOfferWall(),pending:{id:'p',amount:0,place:'qa'}},{...freshSourceOfferWall(),localDebits:[{id:'p',amount:1,place:'qa'},{id:'p',amount:1,place:'qa'}]}])assert.throws(()=>decodeSourceOfferWall(s));});
for(const stage of [0,89,90,99,100,99999])test(`source display stage gate ${stage}`,()=>{assert.equal(sourceOfferWallExposure(stage,true,true,{minDisplayStage:10}).visible,stage>=90);assert(!sourceOfferWallExposure(stage,false,true,{minDisplayStage:10}).visible);assert(!sourceOfferWallExposure(stage,true,false,{minDisplayStage:10}).visible);assert(!sourceOfferWallExposure(stage,true,true,null).visible);});
test('configured initialization connects, preloads and queries, never gives empty balance gems',async()=>{const c=harness();await c.owner.initialize(false);assert.equal(c.requests.length,0);await c.owner.initialize(true);assert(c.owner.connected&&c.owner.contentReady);assert.deepEqual(c.requests.map(q=>q.operation),['connect','content','balance']);assert.equal(c.diamonds,500);assert.equal(c.writes.length,0);await c.owner.initialize(true);assert.equal(c.requests.length,3);});
test('balance must persist before spend, durable debit before wallet grant, duplicate claim gives nothing',async()=>{const c=harness();c.state.localBalance=17;await c.owner.initialize(true);assert.equal(c.diamonds,517);assert.equal(c.state.localBalance,0);assert.equal(c.state.pending,null);assert.equal(c.state.localGrants.length,1);assert.deepEqual(c.writes.map(w=>[w.state.pending?.amount??0,w.state.localBalance,w.diamonds]),[[17,17,500],[17,0,500],[0,0,517]]);await c.owner.claim();assert.equal(c.diamonds,517);assert.equal(c.state.localDebits.length,1);});
test('reservation write failure never reaches SDK spend, explicit retry can complete',async()=>{const c=harness();await c.owner.initialize(true);c.state.localBalance=17;c.fail=s=>!!s.pending;assert(!await c.owner.claim());assert(c.owner.saveFailed);assert.equal(c.state.localBalance,17);assert(!c.requests.some(q=>q.operation==='spend'));c.fail=()=>false;assert(await c.owner.claim());assert.equal(c.diamonds,517);});
test('wallet save failure preserves confirmed pending debit; codec reload recovers without second debit',async()=>{const c=harness();await c.owner.initialize(true);c.state.localBalance=17;c.fail=(s,d)=>d>500;assert(!await c.owner.claim());assert(c.owner.saveFailed);assert.equal(c.diamonds,500);assert.equal(c.state.localBalance,0);assert.equal(c.state.pending.amount,17);assert.equal(c.state.localDebits.length,1);const id=c.state.pending.id,spends=c.requests.filter(q=>q.operation==='spend').length;c.owner.reset();c.state=decodeSourceOfferWall(JSON.parse(JSON.stringify(c.state)));c.fail=()=>false;await c.owner.initialize(true);assert.equal(c.diamonds,517);assert.equal(c.requests.filter(q=>q.operation==='spend').length,spends);assert.deepEqual(c.state.localGrants,[id]);});
test('save unloaded defers credit until loaded then recovers once',async()=>{const c=harness();await c.owner.initialize(true);c.state.localBalance=17;c.saveLoaded=false;assert(!await c.owner.claim());assert.equal(c.diamonds,500);assert(c.state.pending);c.saveLoaded=true;assert(await c.owner.claim());assert.equal(c.diamonds,517);assert(!await c.owner.claim());});
for(const status of ['failure','cancelled','unavailable'])test(`spend ${status} never grants and clears failed reservation`,async()=>{const c=harness();await c.owner.initialize(true);c.state.localBalance=17;c.execute=q=>Promise.resolve({...q,status:q.operation==='spend'?status:'success',provider:'local-test',onlineVerified:false,balance:17,contentReady:true});assert(!await c.owner.claim());assert.equal(c.diamonds,500);assert.equal(c.state.localBalance,17);assert.equal(c.state.pending,null);assert.equal(c.state.localDebits.length,0);});
for(const kind of ['id','operation','place','amount','provider','onlineVerified','balance'])test(`mismatched spend ${kind} is ignored; pending is retained for safe retry`,async()=>{const c=harness();await c.owner.initialize(true);c.state.localBalance=17;c.execute=q=>Promise.resolve({...q,status:'success',provider:'local-test',onlineVerified:false,balance:17,contentReady:true,...(q.operation==='spend'?{[kind]:kind==='amount'?18:kind==='onlineVerified'?true:kind==='balance'?-1:'wrong'}:{})});assert(!await c.owner.claim());assert.equal(c.diamonds,500);assert(c.state.pending);assert.equal(c.state.localDebits.length,0);});
test('provider debit identity survives provider recreation, conflicts and unsolicited debit rejected',async()=>{const c=harness();c.state.localBalance=17;const q={id:'p',operation:'spend',amount:17,place:'qa'};assert.throws(()=>sourceOfferWallDebit(c.state,q));c.state.pending={id:'p',amount:17,place:'qa'};await c.execute(q);assert.equal(c.state.localBalance,0);const p=createLocalOfferWallProvider({available:true,read:()=>c.state,debit:q=>c.write(sourceOfferWallDebit(c.state,q),c.diamonds)});await p.execute(q);assert.equal(c.state.localDebits.length,1);assert.throws(()=>sourceOfferWallDebit(c.state,{...q,amount:18}));assert.equal(sourceOfferWallGrant(c.state,500).diamonds,517);});
for(const kind of ['reset','context','timeout'])test(`late balance ${kind} cannot create pending credit`,async()=>{const c=harness();await c.owner.initialize(true);let resolve;c.execute=q=>new Promise(r=>resolve=()=>r({...q,status:'success',provider:'local-test',onlineVerified:false,balance:17,contentReady:true}));const p=c.owner.claim();assert(c.owner.claiming);if(kind==='reset')c.owner.reset();if(kind==='context')c.contextID='B';if(kind==='timeout'){c.now=20000;c.owner.tick();assert(!c.owner.claiming);}resolve();assert(!await p);assert(!c.state.pending);assert.equal(c.diamonds,500);});
test('reset during SDK content request cannot overwrite a newer context',async()=>{const c=harness();let resolve;c.execute=q=>q.operation==='content'?new Promise(r=>resolve=()=>r({...q,status:'success',provider:'local-test',onlineVerified:false,balance:0,contentReady:true})):Promise.resolve({...q,status:'success',provider:'local-test',onlineVerified:false,balance:0,contentReady:true});const p=c.owner.initialize(true);await flush();c.owner.reset();resolve();await p;assert(!c.owner.connected&&!c.owner.contentReady);});
test('claim timeout after local debit defers recovery and rejects late credit',async()=>{const c=harness();await c.owner.initialize(true);c.state.localBalance=17;let resolve;c.execute=q=>q.operation==='spend'?(c.write(sourceOfferWallDebit(c.state,q),c.diamonds),new Promise(r=>resolve=()=>r({...q,status:'success',provider:'local-test',onlineVerified:false,balance:0,contentReady:true}))):Promise.resolve({...q,status:'success',provider:'local-test',onlineVerified:false,balance:17,contentReady:true});const p=c.owner.claim();await flush();assert.equal(c.state.localBalance,0);c.now=20000;c.owner.tick();resolve();assert(!await p);assert.equal(c.diamonds,500);assert(await c.owner.claim());assert.equal(c.diamonds,517);});
test('close retains same-context callback, repeat queued claim does not duplicate',async()=>{const c=harness();await c.owner.initialize(true);c.state.localBalance=17;let resolve;const orig=c.execute;c.execute=q=>q.operation==='spend'?new Promise(r=>resolve=async()=>r(await orig(q))):orig(q);const p=c.owner.claim();await flush();c.owner.dismiss();resolve();assert(await p);await flush();assert.equal(c.diamonds,517);assert.equal(c.state.localGrants.length,1);assert(!c.owner.open);c.now=3500;c.owner.tick();await flush();assert.equal(c.diamonds,517);});
test('durable debit fields and grant balance overflow are validated',()=>{const s={localBalance:0,pending:{id:'p',amount:17,place:'qa'},localDebits:[{id:'p',amount:18,place:'qa'}],localGrants:[]};assert.throws(()=>decodeSourceOfferWall(s));s.localDebits[0].amount=17;assert.throws(()=>sourceOfferWallGrant(s,Number.MAX_SAFE_INTEGER));});
test('QA service routes and storage are isolated',()=>{for(const n of ['page','shop','hud','locked','pending'])assert(SOURCE_QA_SCENARIOS.includes('offerwall-'+n));let accesses=0;const storage=createSourceQAStorage({getItem(){accesses++;},setItem(){accesses++;}},true);storage.setItem('qa','test');assert.equal(accesses,0);});

test('context change without explicit reset releases the stale SDK request owner',async()=>{const c=harness();await c.owner.initialize(true);let resolve;c.execute=q=>new Promise(r=>resolve=()=>r({...q,status:'success',provider:'local-test',onlineVerified:false,balance:17,contentReady:true}));const p=c.owner.claim();c.contextID='B';resolve();assert(!await p);assert(!c.owner.claiming&&!c.owner.pending&&!c.owner.connected);assert.equal(c.diamonds,500);});
test('wallet overflow is surfaced without throwing or discarding confirmed debit',async()=>{const c=harness();await c.owner.initialize(true);c.diamonds=Number.MAX_SAFE_INTEGER;c.state.localBalance=17;assert(!await c.owner.claim());assert(c.owner.saveFailed);assert.equal(c.state.localDebits.length,1);assert(c.state.pending);assert.equal(c.diamonds,Number.MAX_SAFE_INTEGER);});
test('contradictory failure after durable debit cannot erase recovery identity',async()=>{const c=harness();await c.owner.initialize(true);c.state.localBalance=17;const orig=c.execute;c.execute=async q=>{const r=await orig(q);return q.operation==='spend'?{...r,status:'failure'}:r;};assert(!await c.owner.claim());assert(c.state.pending);assert.equal(c.state.localBalance,0);assert.equal(c.diamonds,500);assert(await c.owner.claim());assert.equal(c.diamonds,517);});
