// STATIC + MODEL/INTERFACE only; not original-device clock, store, or human experience.
import test from 'node:test';import assert from 'node:assert/strict';
import {sourcePassRefresh as refresh,sourcePassStartNext as next,sourcePassRewards as rewards,decodeSourcePassLifecycle as decode,sourcePassAllRewards as all,localSourcePassClock} from '../r6-pass-lifecycle';
import {SourcePassClient} from '../pass-lifecycle-client';
import {freshSourceMetaState,serializeSourceMetaState,decodeSourceMetaState,runtimeSourcePassClaim} from '../source-meta-runtime';
import {createSession,sourceGun} from '../session';import {createActivityState,decodeActivityState,serializeActivityState} from '../source-activities';import {freshPlatformState} from '../local-platform';
const clock=(day='2026-01-31')=>({now:`${day}T14:23:45+08:00`,today:day,canGrantTimedReward:true,pendingCount:0,canRolloverDaily:true,evidence:'TEST local adapter'});
const fresh=()=>({session:{...createSession(),overlay:'none',diamonds:17,gunInventory:[]},activities:createActivityState(),meta:freshSourceMetaState(),platform:freshPlatformState()});
const ready=(day='2026-01-31')=>refresh(fresh(),clock(day)).bundle;
const response=(r,status='success')=>({...r,status,provider:'local-test',onlineVerified:false});
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
function client(options={}){const c={b:ready(),ctx:'A',day:'2026-01-31',fail:false,writes:[],requests:[],notes:[],completed:[]};c.owner=new SourcePassClient({read:()=>({bundle:c.b,contextID:c.ctx}),write:b=>{if(c.fail)throw Error('quota');c.writes.push(b);c.b=b;},clock:()=>clock(c.day),requestID:()=>`pass-test-${c.requests.length}`,notice:n=>c.notes.push(n),allRewardsClaimed:b=>{c.completed.push({bundle:b,writes:c.writes.length});options.allRewardsClaimed?.(b);},execute:q=>{c.requests.push(q);return options.execute?options.execute(q):Promise.resolve(response(q,options.outcome??'success'));}});return c;}
test('source initial and later reward formulas all25/both tracks and recovered8 high-tier guns',()=>{
 assert.deepEqual(rewards(0).filter(r=>r.kind==='gunUnlock').map(r=>r.amount),[10,14,15,19,20,24,25,29]);
 assert.deepEqual(rewards(1).filter(r=>r.kind==='gunUnlock').map(r=>r.amount),[16,18,20,22,24,25,27,29]);
 for(let i=0;i<25;i++){for(const t of [0,1]){const r=rewards(8,true,t)[i];assert.equal(r.requiresAd,t===0&&i>=3&&i%3===0);if(i%3!==2)assert.equal(r.amount,(600+20*i)*(t?3:1));else assert.equal(r.amount,rewards(1)[i].amount+t*5);}}
 assert.equal(rewards(2,false)[2].amount,420);assert.equal(rewards(2,false,1)[23].amount,1890);assert.equal(rewards(2,false)[2].coreType,3);
});
test('fresh season source defaults init without gifting resources then DateTime.AddMonths month clamp',()=>{const b=fresh(),r=refresh(b,clock());assert.equal(r.reset,'init');assert.equal(r.bundle.meta.passLifecycle.seasonEnd,'2026-02-28T14:23:45+08:00');assert.equal(r.bundle.session.diamonds,17);assert.equal(r.bundle.meta.passLifecycle.seasonNumber,0);assert.equal(refresh(r.bundle,clock()).changed,false);});
test('legacy missing lifecycle anchors preserving balances claims exp flags; no migration rewards',()=>{const b=fresh();delete b.meta.passLifecycle;b.activities.passExp=1135;b.activities.passClaims=[0,1];b.meta.epicClaims=[0];b.meta.vip=true;b.session.diamonds=919;b.meta.petCoin=77;const r=refresh(b,clock());assert.equal(r.reset,'legacy-anchor');assert.equal(r.bundle.activities.passExp,1135);assert.deepEqual(r.bundle.activities.passClaims,[0,1]);assert(r.bundle.meta.vip);assert.equal(r.bundle.session.diamonds,919);assert.equal(r.bundle.meta.petCoin,77);assert.deepEqual(r.bundle.meta.epicClaims,[0]);});
test('daily rolls counters/claims, retains both tracks exp and rights; same day not reset',()=>{const b=ready();b.activities.counters['mine-played']=9;b.activities.missionClaims=['mine-1'];b.meta.vipMissionClaims=['vip-1'];b.meta.luxuryMissionClaims=['mine-1'];b.activities.passExp=157;b.activities.passClaims=[0];b.meta.vip=b.meta.luxury=true;b.meta.epicClaims=[0];const r=refresh(b,clock('2026-02-01'));assert.equal(r.reset,'daily');assert.equal(r.bundle.activities.counters['mine-played'],0);assert.deepEqual(r.bundle.meta.vipMissionClaims,[]);assert.deepEqual(r.bundle.meta.luxuryMissionClaims,[]);assert.equal(r.bundle.activities.passExp,157);assert(r.bundle.meta.luxury);assert.deepEqual(r.bundle.meta.epicClaims,[0]);assert.equal(refresh(r.bundle,clock('2026-02-01')).changed,false);assert.equal(refresh(r.bundle,clock()).changed,false);});
test('season expiry clears pass rights/claims/task, keeps all other source balances; no auto grant',()=>{const b=ready();b.activities.passExp=2517;b.activities.passClaims=[0];b.meta.vip=b.meta.luxury=true;b.meta.petCoin=39;b.meta.adventure.cores[3]=19;const r=refresh(b,clock('2026-02-28'));assert.equal(r.reset,'season');assert.equal(r.bundle.meta.passLifecycle.seasonNumber,1);assert.equal(r.bundle.meta.passLifecycle.seasonEnd,'2026-03-28T14:23:45+08:00');assert.equal(r.bundle.activities.passExp,0);assert.equal(r.bundle.activities.season,'later');assert(!r.bundle.meta.vip);assert.equal(r.bundle.session.diamonds,17);assert.equal(r.bundle.meta.petCoin,39);assert.equal(r.bundle.meta.adventure.cores[3],19);assert.equal(r.bundle.meta.passLifecycle.history[0].exp,17);assert.equal(r.bundle.meta.passLifecycle.history[0].reason,'expired');});
for(const change of [{canGrantTimedReward:false},{pendingCount:1},{canGrantTimedReward:null},{pendingCount:null}])test(`unknown/deferred source time gate ${JSON.stringify(change)} does not force expiry`,()=>{const b=ready(),r=refresh(b,{...clock('2026-03-01'),...change});assert.notEqual(r.reset,'season');assert.equal(r.bundle.meta.passLifecycle.seasonNumber,0);});
test('local monotonic day updated even if daily rollover is deferred',()=>{const r=refresh(ready(),{...clock('2026-02-01'),canRolloverDaily:false});assert.equal(r.bundle.meta.passLifecycle.lastAcceptedDay,'2026-02-01');assert.equal(refresh(r.bundle,clock()).changed,false);});
test('manual new season gate requires normal25 and VIP epic25; no automatic claim',()=>{const b=ready();b.activities.passExp=2500;assert(!all(b));assert(!next(b,clock()).changed);b.activities.passClaims=Array.from({length:25},(_,i)=>i);assert(all(b));b.meta.vip=true;assert(!all(b));b.meta.epicClaims=[...b.activities.passClaims];assert(all(b));const r=next(b,clock());assert.equal(r.reset,'season');assert.equal(r.bundle.meta.passLifecycle.seasonNumber,1);assert.equal(r.bundle.meta.passLifecycle.history[0].reason,'all-rewards');assert.equal(r.bundle.session.diamonds,17);assert(!r.bundle.meta.vip);});
test('history48 adapter retained oldest pruned; validated order',()=>{let b=ready();for(let i=0;i<52;i++){b.activities.passClaims=Array.from({length:25},(_,j)=>j);b.activities.passExp=2500;b=next(b,clock()).bundle;}assert.equal(b.meta.passLifecycle.history.length,48);assert.equal(b.meta.passLifecycle.history[0].seasonNumber,4);assert.deepEqual(decode(b.meta.passLifecycle),b.meta.passLifecycle);});
test('lifecycle/activities codec accepts later rewards and no legacy mutation',()=>{const b=refresh(ready(),clock('2026-02-28')).bundle;assert.equal(decodeActivityState(serializeActivityState(b.activities)).season,'later');assert.deepEqual(decodeSourceMetaState(serializeSourceMetaState(b.meta)).passLifecycle,b.meta.passLifecycle);const raw=JSON.parse(serializeSourceMetaState(b.meta));delete raw.passLifecycle;assert.equal(decodeSourceMetaState(JSON.stringify(raw)).passLifecycle,undefined);});
for(const change of [{seasonNumber:-1},{seasonNumber:1.5},{seasonStarted:1},{seasonEnd:'2026-02-30T00:00:00Z'},{lastAcceptedDay:'0000-01-01'},{missionStart:null},{history:[{}]},{history:[{seasonNumber:9}]}])test(`invalid lifecycle ${Object.keys(change)} rejected`,()=>assert.throws(()=>decode({...ready().meta.passLifecycle,...change})));
test('later Core source type3 only + ad scoped by season and receipt',()=>{const b=ready();b.meta.passLifecycle.seasonNumber=2;b.meta.passLifecycle.gunSeason=false;b.activities.passExp=300;b.activities.passClaims=[0,1];b.meta.adventure.cores=[2,3,4,5];const r=runtimeSourcePassClaim(b,0,2,{adConfirmed:false});assert.equal(r.status,'granted');assert.deepEqual(r.meta.adventure.cores,[2,3,4,425]);assert.equal(r.meta.petCoin,b.meta.petCoin);assert.equal(r.session.starGem,b.session.starGem);r.activities.passExp=400;const ad=runtimeSourcePassClaim(r,0,3,{adConfirmed:true,requestID:'season-two-ad'});assert(ad.platform.claims.includes('meta:local-pass:season-two-ad'));});
test('Core overflow/full gun inventory cannot consume claim or partially grant',()=>{const b=ready();b.meta.passLifecycle.seasonNumber=1;b.meta.passLifecycle.gunSeason=false;b.activities.passExp=300;b.activities.passClaims=[0,1];b.meta.adventure.cores[3]=Number.MAX_SAFE_INTEGER;assert.equal(runtimeSourcePassClaim(b,0,2).status,'blocked');assert.deepEqual(b.activities.passClaims,[0,1]);b.meta.passLifecycle.gunSeason=true;b.session.gunInventory=Array.from({length:16},()=>sourceGun(0));assert.equal(runtimeSourcePassClaim(b,0,2).status,'blocked');});
for(const status of ['failure','cancelled','unavailable'])test(`provider ${status} changes no wallet/pass`,async()=>{const c=client({outcome:status});assert(!await c.owner.purchase('vip'));assert.equal(c.b.session.diamonds,17);assert(!c.b.meta.vip);assert.equal(c.writes.length,0);});
test('purchase callback reads current wallet & claims; pending duplicate prevented, audit one',async()=>{const d=deferred(),c=client({execute:()=>d.promise});c.b.activities.passExp=100;const p=c.owner.purchase('vip');assert(c.owner.pending);assert(!await c.owner.purchase('vip'));c.b.session.diamonds=99;c.b.activities.passClaims=[0];d.resolve(response(c.requests[0]));assert(await p);assert.equal(c.b.session.diamonds,599);assert(c.b.meta.vip);assert.deepEqual(c.b.activities.passClaims,[0]);assert.equal(c.b.platform.claims.length,1);assert(!await c.owner.purchase('vip'));});
test('luxury from free/upgrade each grant1000+300 only once and preserve capped overflow',async()=>{const c=client();assert(!await c.owner.purchase('luxury-upgrade'));assert(await c.owner.purchase('luxury'));assert.equal(c.b.session.diamonds,1017);assert.equal(c.b.activities.passExp,300);assert(c.b.meta.luxury&&c.b.meta.vip);assert(!await c.owner.purchase('luxury'));const u=client();assert(await u.owner.purchase('vip'));u.b.activities.passExp=2499;assert(await u.owner.purchase('luxury-upgrade'));assert.equal(u.b.activities.passExp,2799);assert.equal(u.b.session.diamonds,1517);});
for(const invalid of ['epoch','context','season','id','purpose','kind','provider','online'])test(`late/mismatched callback ${invalid} no grant`,async()=>{const d=deferred(),c=client({execute:()=>d.promise});const p=c.owner.purchase('vip');const r=response(c.requests[0]);if(invalid==='epoch')c.owner.invalidate();else if(invalid==='context')c.ctx='B';else if(invalid==='season')c.day='2026-02-28';else if(invalid==='online')r.onlineVerified=true;else r[invalid]='wrong';d.resolve(r);assert(!await p);assert(!c.b.meta.vip);assert.equal(c.b.session.diamonds,17);});
test('quota retry retains callback but current wallet; never executes provider again',async()=>{const c=client();c.fail=true;assert(!await c.owner.purchase('vip'));assert(c.owner.saveFailed&&c.owner.pending);assert.equal(c.b.session.diamonds,17);c.fail=false;c.b.session.diamonds=44;assert(c.owner.retrySave());assert.equal(c.b.session.diamonds,544);assert.equal(c.requests.length,1);assert(!c.owner.retrySave());});
test('ad claim saves flags and actual receipt once; not the fixed slot ledger',async()=>{const c=client();c.b.activities.passExp=400;c.b.activities.passClaims=[0,1,2];assert(await c.owner.claim(0,3));assert.equal(c.requests[0].kind,'ad');assert.equal(c.b.session.diamonds,337);assert(c.b.platform.claims.includes('meta:local-pass:pass-test-0'));assert(!await c.owner.claim(0,3));assert.equal(c.requests.length,1);});
test('nonad claim quota retry no provider; removed ads skip provider and preserves pass position',async()=>{const c=client();c.b.activities.passExp=400;c.b.activities.passClaims=[0,1,2];c.b.meta.entitlements.removeAdsAll=true;c.fail=true;assert(!await c.owner.claim(0,3));assert.deepEqual(c.b.activities.passClaims,[0,1,2]);c.fail=false;assert(await c.owner.claim(0,3));assert.equal(c.requests.length,0);});
test('throwing provider and purchase overflow no partial publish; callback recovery not stuck',async()=>{const c=client({execute:()=>{throw Error('test');}});assert(!await c.owner.purchase('vip'));assert(!c.owner.pending);const o=client();o.b.session.diamonds=Number.MAX_SAFE_INTEGER;assert(!await o.owner.purchase('vip'));assert(!o.b.meta.vip);assert.equal(o.writes.length,0);assert(!o.owner.pending);});
test('explicit local clock records adapter disclosure and exact local calendar',()=>{const c=localSourcePassClock(new Date(2026,0,31,14,23,45));assert.equal(c.today,'2026-01-31');assert(c.now.startsWith('2026-01-31T14:23:45'));assert(c.evidence.includes('未连接'));});

// Source Check_All_Reward_Get consumer; opening forced is an event, not a loop.
const allButLast=(c,vip=false,ad=false)=>{c.b.activities.passExp=2500;c.b.meta.vip=vip;c.b.activities.passClaims=Array.from({length:vip?25:24},(_,i)=>i);c.b.meta.epicClaims=Array.from({length:vip?24:0},(_,i)=>i);if(ad)c.b.meta.vip=false;};
test('last normal claim emits completion after persist; nonfinal/repeat never emit',async()=>{const c=client();c.b.activities.passExp=100;assert(await c.owner.claim(0,0));assert.equal(c.completed.length,0);allButLast(c);assert(await c.owner.claim(0,24));assert.equal(c.completed.length,1);assert.equal(c.completed[0].bundle,c.b);assert.equal(c.completed[0].writes,c.writes.length);assert(all(c.b));assert(!await c.owner.claim(0,24));assert.equal(c.completed.length,1);});
test('VIP all-normal does not complete until final epic; privilege consumers distinct',async()=>{const c=client();allButLast(c,true);assert(!all(c.b));assert(await c.owner.claim(1,24));assert.equal(c.completed.length,1);assert(all(c.b));});
test('last claim write failure never emits; retry has one postcommit completion',async()=>{const c=client();allButLast(c);c.b.meta.entitlements.removeAdsAll=true;c.fail=true;assert(!await c.owner.claim(0,24));assert.equal(c.completed.length,0);assert(!all(c.b));c.fail=false;assert(await c.owner.claim(0,24));assert.equal(c.completed.length,1);});
test('ad last claim save recovery emits once without second provider',async()=>{const c=client();allButLast(c,false,true);c.fail=true;assert(!await c.owner.claim(0,24));assert(c.owner.saveFailed);assert.equal(c.completed.length,0);c.fail=false;assert(c.owner.retrySave());assert.equal(c.completed.length,1);assert.equal(c.requests.length,1);assert(!c.owner.retrySave());assert(!await c.owner.claim(0,24));assert.equal(c.completed.length,1);});
for(const mode of ['context','invalidate','season'])test(`last ad callback invalidated by ${mode} cannot emit`,async()=>{const d=deferred(),c=client({execute:()=>d.promise});allButLast(c,false,true);const p=c.owner.claim(0,24);if(mode==='context')c.ctx='B';else if(mode==='invalidate')c.owner.invalidate();else c.day='2026-02-28';d.resolve(response(c.requests[0]));assert(!await p);assert.equal(c.completed.length,0);});
for(const status of ['failure','cancelled','unavailable'])test(`last claim provider ${status} cannot emit`,async()=>{const c=client({outcome:status});allButLast(c,false,true);assert(!await c.owner.claim(0,24));assert.equal(c.completed.length,0);assert(!all(c.b));});
test('refresh, recreated client, purchase, mission and next cannot open forced again',async()=>{const c=client();allButLast(c);assert(await c.owner.claim(0,24));assert.equal(c.completed.length,1);assert(c.owner.refresh());assert(c.owner.refresh());assert.equal(c.completed.length,1);assert(c.owner.next());assert.equal(c.completed.length,1);assert.equal(c.b.activities.passClaims.length,0);assert(c.owner.refresh());assert.equal(c.completed.length,1);const p=client();p.b.activities.passExp=2500;p.b.activities.passClaims=Array.from({length:25},(_,i)=>i);assert(await p.owner.purchase('vip'));assert.equal(p.completed.length,0);});
test('presentation callback failure does not falsely report commit failure',async()=>{const c=client({allRewardsClaimed:()=>{throw Error('UI');}});allButLast(c);assert(await c.owner.claim(0,24));assert(all(c.b));assert.equal(c.completed.length,1);assert(!c.notes.some(n=>n.includes('未部分发奖')));});

test('recreated owner at all-claimed state never emits on refresh or repeated claim',async()=>{const c=client();c.b.activities.passExp=2500;c.b.activities.passClaims=Array.from({length:25},(_,i)=>i);assert(c.owner.refresh());assert.equal(c.completed.length,0);assert(!await c.owner.claim(0,24));assert.equal(c.completed.length,0);});
