import test from 'node:test';import assert from 'node:assert/strict';
import tree from '../data/source-ui-tree.json';
import {sourcePassPopupProjection,SOURCE_PASS_POPUP_ROOTS}from '../pass-popup-projection.ts';
import {createSession}from '../session.ts';import {createActivityState}from '../source-activities.ts';import {freshPlatformState}from '../local-platform.ts';import {freshSourceMetaState}from '../source-meta-runtime.ts';
import {sourcePassRefresh}from '../r6-pass-lifecycle.ts';import {SourcePassClient}from '../pass-lifecycle-client.ts';
const clock={now:'2026-01-31T12:00:00+08:00',today:'2026-01-31',canGrantTimedReward:true,pendingCount:0,canRolloverDaily:true,evidence:'isolated test'};
const ready=()=>sourcePassRefresh({session:createSession(),activities:createActivityState(),platform:freshPlatformState(),meta:freshSourceMetaState()},clock).bundle;
const path=id=>tree.nodes.find(n=>n.id==='level0:'+id).path;
test('source purchase opens real popup, cards/old inactive ancestors stay source-owned',()=>{const b=ready(),p=sourcePassPopupProjection(tree,b,'vip');assert.equal(p.active[SOURCE_PASS_POPUP_ROOTS.vip],true);assert.equal(p.active[SOURCE_PASS_POPUP_ROOTS.luxury],false);for(const id of [2040,1841,22720,37385])assert.equal(p.bindings.get(path(id)).payload,'vip');assert.equal(p.bindings.get(path(11664)).payload,'luxury');assert.equal(p.active[SOURCE_PASS_POPUP_ROOTS.vip+'/Panel'],undefined);assert.equal(p.active[SOURCE_PASS_POPUP_ROOTS.vip+'/Panel/VIP_Pass_ui'],undefined);});
test('VIP owned / selected Luxury upgrade is independent and keeps popup return',()=>{const b=ready();b.meta.vip=true;const p=sourcePassPopupProjection(tree,b,'luxury');assert.equal(p.active[path(28549)],true);assert.equal(p.active[path(37385)],false);assert.equal(p.bindings.get(path(17541)).payload,'luxury-upgrade');assert.equal(p.active[path(33141)],true);assert.equal(p.active[path(35982)],false);assert.equal(p.bindings.get(path(1964)).name,'pass-popup-close');b.meta.luxury=true;const owned=sourcePassPopupProjection(tree,b,'luxury');assert.equal(owned.active[path(31074)],true);assert.equal(owned.active[path(17541)],false);});
test('new season promo is source 3-item epic window, disabled fixed-slot demos never activated',()=>{const b=ready();b.activities.passExp=2400;const p=sourcePassPopupProjection(tree,b,'next');const a=SOURCE_PASS_POPUP_ROOTS.next+'/VIP Panel (Inapp)/Panel/Reward_list/Mission_Reward_Epic';assert.equal(p.text[a+'/Dia/Dia_Value'],String((200+40*21)*3));assert.equal(p.active[a+'/Dia'],true);assert.equal(p.active[a+' (2)/Gun'],true);for(const id of [5634,5632,5636,5633,5635,5631]){assert.equal(tree.nodes.find(n=>n.id==='level0:'+id).components.find(c=>c.kind==='Button').enabled,false);assert.equal(p.bindings.has(path(id)),false);}assert.equal(p.bindings.get(path(128)).name,'pass-banner-purchase');assert.equal(p.bindings.get(path(1571)).name,'pass-next');});
test('later season Core3 preview is not PetCoin/StarGem and updates amount',()=>{const b=ready();b.activities.passExp=300;b.meta.passLifecycle.seasonNumber=1;b.meta.passLifecycle.gunSeason=false;const p=sourcePassPopupProjection(tree,b,'next'),a=SOURCE_PASS_POPUP_ROOTS.next+'/VIP Panel (Inapp)/Panel/Reward_list/Mission_Reward_Epic (2)';assert.equal(p.active[a+'/Core'],true);assert.equal(p.active[a+'/Gun'],false);assert.equal(p.text[a+'/Core/Core_Value'],'1260');});
test('all enabled popup Buttons bound, disabled buttons retained as native disabled evidence',()=>{const b=ready(),p=sourcePassPopupProjection(tree,b,'none');for(const n of tree.nodes)if(Object.values(SOURCE_PASS_POPUP_ROOTS).some(root=>n.path.startsWith(root+'/'))&&n.components.some(c=>c.kind==='Button'&&c.enabled!==false))assert(p.bindings.has(n.path),n.path);});
test('failed initialization save cannot recursively refresh from the presentation notice',()=>{let b={session:createSession(),activities:createActivityState(),platform:freshPlatformState(),meta:freshSourceMetaState()},notices=0,owner;owner=new SourcePassClient({read:()=>({bundle:b,contextID:'test'}),write:()=>{throw Error('quota');},clock:()=>clock,execute:async()=>{throw Error('unused');},requestID:()=>'',notice(){notices++;assert.equal(owner.refresh(),false);}});assert.equal(owner.refresh(),false);assert.equal(notices,1);assert.equal(b.meta.passLifecycle.seasonStarted,false);});
import slotMap from '../data/r6-pass-slots.json';
import {sourceMissionPanelProjection}from '../source-panel-bindings.ts';
test('serialized 25 reward slots start at physical slot1 / Lv2; Lv1 spacer never gets a reward action',()=>{
 const b=ready(),p=sourceMissionPanelProjection({...b,textures:{},viewport:{width:390,height:844},panel:'pass',action(){}});
 assert.equal(slotMap.slots.length,25);
 for(const slot of slotMap.slots){assert.equal(p.text[slot.path+'/Slot/Lv_txt'],String(slot.index+2));for(const track of [0,1])assert.deepEqual(p.bindings.get(slot.path+(track===0?'/Mission_Reward_Normal':'/Mission_Reward_Epic')),{name:'pass-claim',payload:{track,index:slot.index}});}
 for(const excluded of slotMap.excludedButtons)assert.equal(p.bindings.has(excluded.path),false,excluded.path);
 assert.equal(p.active[slotMap.spacer.path+'/Mission_Reward_Normal'],undefined);assert.equal(p.text['/Canvas/SafeArea/Mission_maanger/Mission_UI/Reward/EXP_Slider/Lv_txt'],'Lv.1');
});

test('forced uses original distinct root/buttons and VIP ownership hides upsell',()=>{const b=ready(),root=SOURCE_PASS_POPUP_ROOTS.forced;const free=sourcePassPopupProjection(tree,b,'forced');assert.equal(free.active[root],true);assert.equal(free.active[SOURCE_PASS_POPUP_ROOTS.next],false);assert.equal(free.active[root+'/VIP Panel (Inapp)'],true);assert.equal(free.bindings.get(path(1227)).name,'pass-next');assert.equal(free.bindings.get(path(987)).name,'pass-banner-purchase');b.meta.vip=true;assert.equal(sourcePassPopupProjection(tree,b,'forced').active[root+'/VIP Panel (Inapp)'],false);});
