// Static/model provider contract; no real ad, device, Storage or source-server proof.
import test from 'node:test';import assert from 'node:assert/strict';
import {SourcePetDailyClient} from '../pet-daily-client';
import {freshSourceMetaState} from '../source-meta-runtime';
import {createSession} from '../session';import {createActivityState} from '../source-activities';import {freshPlatformState} from '../local-platform';
import {sourcePetWithIdentities} from '../r5-pet';
const response=(q,status='success')=>({...q,status,provider:'local-test',onlineVerified:false});
function fixture(options={}){const c={ctx:'A',day:'20261004',writes:0,fail:false,notes:[],requests:[],b:{session:{...createSession(),mode:'field',historicMax:110,diamonds:3000},activities:createActivityState(),platform:freshPlatformState(),meta:freshSourceMetaState()}};c.b.meta.hunt.level=1;c.b.meta.pet.owned=[0,...Array(15).fill(-1)];c.b.meta.pet=sourcePetWithIdentities(c.b.meta.pet);c.owner=new SourcePetDailyClient({read:()=>({bundle:c.b,contextID:c.ctx}),write:b=>{if(c.fail)throw Error('save');c.b=b;c.writes++;},todayKey:()=>c.day,requestID:()=>`daily-${c.requests.length}`,execute:q=>{c.requests.push(q);return options.execute?options.execute(q):Promise.resolve(response(q,options.outcome??'success'));},notice:n=>c.notes.push(n)});return c;}
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve};};
test('type11 success persists C pet and receipt once',async()=>{const c=fixture();assert(await c.owner.request());assert.equal(c.b.meta.pet.owned[1],1);assert.equal(c.b.meta.pet.dailyLastDate,'20261004');assert.equal(c.b.platform.claims.length,1);assert.equal(c.b.platform.sequence,1);assert.equal(c.writes,1);assert(!await c.owner.request());assert.equal(c.writes,1);});
for(const outcome of ['failure','cancelled','unavailable'])test(`provider ${outcome} never grants or consumes day`,async()=>{const c=fixture({outcome});assert(!await c.owner.request());assert.equal(c.b.meta.pet.dailyLastDate,'');assert.equal(c.b.meta.pet.owned[1],-1);assert.equal(c.b.platform.sequence,0);});
test('late callback after context change is rejected',async()=>{const d=deferred(),c=fixture({execute:()=>d.promise});const p=c.owner.request();assert.equal(c.requests.length,1);c.ctx='B';d.resolve(response(c.requests[0]));assert(!await p);assert.equal(c.b.meta.pet.owned[1],-1);assert.equal(c.writes,0);});
test('save failure recovers without replaying ad',async()=>{const c=fixture();c.fail=true;assert(!await c.owner.request());assert(c.owner.saveFailed);assert.equal(c.requests.length,1);c.fail=false;assert(c.owner.retrySave());assert.equal(c.b.meta.pet.owned[1],1);assert.equal(c.requests.length,1);assert.equal(c.writes,1);assert(!c.owner.retrySave());});
test('callback-time full inventory leaves daily unused',async()=>{const d=deferred(),c=fixture({execute:()=>d.promise});const p=c.owner.request();c.b.meta.pet.owned=Array.from({length:16},(_,i)=>i%10);d.resolve(response(c.requests[0]));assert(!await p);assert.equal(c.b.meta.pet.dailyLastDate,'');assert.equal(c.b.platform.sequence,0);});
test('invalidate drops pending response',async()=>{const d=deferred(),c=fixture({execute:()=>d.promise});const p=c.owner.request();c.owner.invalidate();d.resolve(response(c.requests[0]));assert(!await p);assert.equal(c.b.meta.pet.dailyLastDate,'');});
