// STATIC + MODEL/INTERFACE. Does not prove source-device clock/store or human experience.
import test from 'node:test';import assert from 'node:assert/strict';
import {SOURCE_RAID_MISSION as C,freshSourceRaidMission as fresh,decodeSourceRaidMission,sourceRaidMissionRefresh as refresh,sourceRaidMissionState as state,sourceRaidMissionOrder as order,sourceRaidMissionProgress as progress,sourceRaidMissionHasClaimable as has,sourceRaidMissionReClaimableReward as sum,sourceRaidMissionClaim as claim,sourceRaidMissionClaimAll as all,sourceRaidMissionTicketRequest as request,sourceRaidMissionTicketReward as reward} from '../r6-raid-mission';
import {SourceRaidMissionClient} from '../raid-mission-client';
import {SOURCE_RAID_MISSION_ITEMS as items,sourceRaidMissionBindings as bindings,sourceRaidMissionProjection as projection,sourceRaidMissionHUD} from '../raid-mission-ui-state';
import {freshSourceRaid,sourceRaidSeason,sourceRaidTickets,sourceRaidAutoSelect,sourceRaidWeakType} from '../r6-raid';
import {createSession,sourceGun} from '../session';import {freshSourceMetaState,decodeSourceMetaState,serializeSourceMetaState} from '../source-meta-runtime';
import {SourceRaidSessionBridge} from '../raid-session-bridge';import {createActivityState} from '../source-activities';import {freshPlatformState} from '../local-platform';import {createLocalMineTime} from '../mine-time';
const raid=(tries=7,best=30)=>({...freshSourceRaid(),seasonIndex:7,tryCount:tries,bestLevel:best});
const response=(r,status='success')=>({...r,status,provider:'local-test',onlineVerified:false});
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),get resolve(){return resolve;}}};
function bundle(){return {session:{...createSession(7),historicMax:390,starGem:20},meta:{...freshSourceMetaState(),raid:raid()},activities:createActivityState(),platform:freshPlatformState()};}
function client(o={}){let b=bundle(),ctx='A',fail=false,seq=0,popups=0;const requests=[],writes=[],notices=[];const owner=new SourceRaidMissionClient({read:()=>({bundle:b,contextID:ctx}),write(next){if(fail)throw Error('quota');writes.push(next);b=next;},execute(r){requests.push(r);return o.execute?.(r)??Promise.resolve(response(r,o.outcome??'success'));},requestID:()=>`test:${++seq}`,notice:m=>notices.push(m),ticketPopup:()=>popups++});return {owner,requests,writes,notices,get b(){return b;},set b(v){b=v;},set ctx(v){ctx=v;},set fail(v){fail=v;},get popups(){return popups;}};}
test('source8 table, purchase product and serialized fallback price',()=>{assert.deepEqual(C.missions.map(m=>[m.type,m.goal,m.reward]),[[0,1,300],[0,4,500],[0,7,800],[1,1,200],[1,5,300],[1,10,400],[1,20,500],[1,30,600]]);assert.equal(C.product,'catgunner_raid_mission_ticket');assert.equal(C.defaultPrice,'$4.99');});
for(let i=0;i<8;i++)test(`mission ${i} source threshold/value/state/reward/progress`,()=>{const m=C.missions[i],r=raid(m.type===0?m.goal-1:0,m.type===1?m.goal-1:0),s=refresh(fresh(),r);assert.equal(state(s,i),0);assert.equal(claim(s,r,i).granted,0);assert.equal(progress(s,r,i).fraction,Math.fround(Math.fround(m.goal-1)/Math.fround(m.goal)));r[m.type===0?'tryCount':'bestLevel']=m.goal;const c=claim(s,r,i);assert.equal(c.granted,m.reward);assert.equal(state(c.state,i),2);assert.equal(progress(c.state,raid(0,0),i).current,m.goal);assert.equal(claim(c.state,r,i).granted,0);assert.equal(claim(c.state,r,i,true).ticketPopup,true);const second=claim({...c.state,ticketPurchased:true},r,i,true);assert.equal(second.granted,m.reward);assert.equal(state(second.state,i),3);assert.equal(claim(second.state,r,i,true).granted,0);});
test('sticky clear in week, all three flags/ticket reset at boundary but provider receipts persist',()=>{const r=raid(),s={...all(refresh(fresh(),r),r).state,ticketPurchased:true,ticketClaims:['purchase:old']};assert(refresh(s,raid(0,0)).clear.every(Boolean));const n=refresh(s,{...raid(0,0),seasonIndex:8});assert.equal(n.seasonIndex,8);assert(n.clear.every(v=>!v)&&n.rewardGet.every(v=>!v)&&n.rewardReGet.every(v=>!v));assert(!n.ticketPurchased);assert.deepEqual(n.ticketClaims,['purchase:old']);});
test('order uses source priority then type/index, not visual pool node ordering',()=>{const s=refresh(fresh(),raid());s.clear[2]=false;s.rewardGet[1]=true;s.rewardGet[4]=true;s.rewardGet[6]=true;s.rewardReGet[6]=true;assert.deepEqual(order(s),[0,3,5,7,1,4,2,6]);assert.deepEqual(order({...s,ticketPurchased:true}),[0,1,3,4,5,7,2,6]);});
test('reclaimable includes not-yet-first-claimed; claimAll is single index pass',()=>{const s=refresh(fresh(),raid());assert.equal(sum(s),3600);assert(has(s));const a=all({...s,ticketPurchased:true},raid());assert.equal(a.granted,3600);assert(a.state.rewardGet.every(Boolean));assert(a.state.rewardReGet.every(v=>!v));const b=all(a.state,raid());assert.equal(b.granted,3600);assert(!has(b.state));assert.equal(sum(b.state),0);assert.equal(all(b.state,raid()).granted,0);assert(!has(all(s,raid()).state));});
test('decoder clones8 flags, rejects corrupt/duplicate receipts and out of range fields',()=>{const s=fresh(),d=decodeSourceRaidMission(s);d.clear[0]=true;assert(!s.clear[0]);for(const bad of [{clear:[false]},{ticketClaims:['x','x']},{rewardGet:Array(8).fill(0)},{seasonIndex:2**31},{ticketPurchased:1}])assert.throws(()=>decodeSourceRaidMission({...s,...bad}));});
test('old meta missing entire field migrates fresh, balances and prior rights unaltered',()=>{const m=freshSourceMetaState();m.petCoin=987;m.entitlements.plusPack2Active=true;const raw=JSON.parse(serializeSourceMetaState(m));delete raw.raidMission;const decoded=decodeSourceMetaState(JSON.stringify(raw));assert.deepEqual(decoded.raidMission,fresh());assert.equal(decoded.petCoin,987);assert(decoded.entitlements.plusPack2Active);assert.deepEqual(decodeSourceMetaState(serializeSourceMetaState(decoded)).raidMission,fresh());});
for(const status of ['failure','cancelled','unavailable'])test(`ticket provider ${status} never grants or issues rewards`,async()=>{const c=client({outcome:status});assert(!await c.owner.purchase());assert(!c.b.meta.raidMission.ticketPurchased);assert.equal(c.b.session.starGem,20);assert.equal(c.writes.length,0);});
test('ticket success only entitlement, duplicate and old-week callback blocked',()=>{const r=raid(),q=request(fresh(),r,390,'p');const a=reward(fresh(),r,q,response(q),390);assert.equal(a.status,'granted');assert(a.state.ticketPurchased);assert(a.state.rewardGet.every(v=>!v));assert.equal(reward(a.state,r,q,response(q),390).status,'blocked');assert.equal(reward(a.state,{...r,seasonIndex:8},q,response(q),390).status,'blocked');for(const diff of [{id:'other'},{purpose:'other'},{kind:'ad'}])assert.equal(reward(fresh(),r,q,{...response(q),...diff},390).status,'blocked');assert.equal(request(fresh(),r,389,'p'),null);});
test('purchase pending rejects duplicate, current wallet/claims are preserved at callback',async()=>{const d=deferred(),c=client({execute:()=>d.promise});const promise=c.owner.purchase();assert(c.owner.pending);assert(!await c.owner.purchase());assert(c.owner.claim(0));c.b={...c.b,session:{...c.b.session,starGem:c.b.session.starGem+77}};d.resolve(response(c.requests[0]));assert(await promise);assert.equal(c.requests.length,1);assert.equal(c.b.session.starGem,397);assert(c.b.meta.raidMission.rewardGet[0]);assert(c.b.meta.raidMission.ticketPurchased);assert(!await c.owner.purchase());});
for(const invalidate of ['epoch','context','week'])test(`late purchase rejected on ${invalidate}`,async()=>{const d=deferred(),c=client({execute:()=>d.promise});const p=c.owner.purchase();if(invalidate==='epoch')c.owner.invalidate();else if(invalidate==='context')c.ctx='B';else c.b={...c.b,meta:{...c.b.meta,raid:{...c.b.meta.raid,seasonIndex:8}}};d.resolve(response(c.requests[0]));assert(!await p);assert.equal(c.writes.length,0);});
test('quota failure retried with same callback, no second transaction or stale wallet rewrite',async()=>{const c=client();c.fail=true;assert(!await c.owner.purchase());assert(c.owner.pending&&c.owner.saveFailed);c.fail=false;assert(c.owner.claim(0));const before=c.b.session.starGem;assert(c.owner.retrySave());assert.equal(c.requests.length,1);assert.equal(c.b.session.starGem,before);assert(c.b.meta.raidMission.rewardGet[0]);assert(!c.owner.retrySave());});
test('claim save failure/repeated claim/overflow keep balances and flags atomic',()=>{const c=client();c.fail=true;assert(!c.owner.claim(0));assert.equal(c.b.session.starGem,20);assert(!c.b.meta.raidMission.rewardGet[0]);c.fail=false;assert(c.owner.claim(0));assert(!c.owner.claim(0));assert(!c.owner.claim(0,true));assert.equal(c.popups,1);c.b={...c.b,session:{...c.b.session,starGem:Number.MAX_SAFE_INTEGER}};assert(!c.owner.claim(1));assert(!c.b.meta.raidMission.rewardGet[1]);});
test('normal gate rejects claim/all without altering save; ticket no premature grant',async()=>{const c=client();c.b.session.historicMax=389;assert(!c.owner.claim(0));assert(!c.owner.claimAll());assert(!await c.owner.purchase());assert.equal(c.writes.length,0);});
test('UI source8 PPtr pool, every source button bound incl explicit Locked/no test activation',()=>{assert.deepEqual(items.map(r=>r.component),[142407,139487,139486,139491,139488,139489,139490,139492]);assert.equal(new Set(bindings.map(b=>b.id)).size,C.buttons.length);assert(bindings.filter(b=>b.action==='raid-mission-source-test').length===2);assert(bindings.filter(b=>b.action==='raid-mission-locked').length===8);assert(bindings.some(b=>b.id==='level0:1934'&&b.action==='raid-mission'));const p=projection(fresh(),raid(),Date.UTC(2026,9,4));assert(!p.active['level0:1634']);assert(!('level0:542'in p.active));assert(sourceRaidMissionHUD(p.state).active['level0:2300']);});
test('real bridge Start/contacts/result mission consumers and changed mission ownership refusal',()=>{const date=new Date(2026,9,4),b=bundle();b.session.equippedGuns=[{...sourceGun(30),uid:'cat-a'},null,null];b.meta.raid=sourceRaidTickets(sourceRaidSeason(freshSourceRaid(),date),createLocalMineTime(()=>date));const host=new SourceRaidSessionBridge('mission-live',b,sourceRaidAutoSelect(b.session,sourceRaidWeakType(b.meta.raid.seasonIndex)));host.prepared();let live=host.startFree(b).bundle;assert.equal(live.meta.raid.tryCount,1);assert(live.meta.raidMission.clear[0]);assert.equal(live.session.starGem,20);const altered={...live,meta:{...live.meta,raidMission:{...live.meta.raidMission,rewardGet:[true,...Array(7).fill(false)]}}};assert.equal(host.commit(altered).status,'blocked');});
