// MODEL/INTERFACE only: local-test receipts; no real store, player Storage or original-device proof.
import test from 'node:test';import assert from 'node:assert/strict';
import {SourceShopPurchaseClient,sourceShopPurchaseRequestGate} from '../shop-purchase-client';
import {createSession,serializeSession,deserializeSession} from '../session';
import {freshSourceMetaState,decodeSourceMetaState,serializeSourceMetaState} from '../source-meta-runtime';
import {createActivityState} from '../source-activities';import {freshPlatformState,decodePlatformState} from '../local-platform';
import {SOURCE_PACKAGE_OFFERS} from '../r5-entitlements';import contract from '../data/round3-ui-contract.json';
const resp=(q,status='success')=>({...q,status,provider:'local-test',onlineVerified:false});
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve};};
function fixture(opts={}){
 const c={ctx:'A',fail:false,writes:0,requests:[],notes:[],shown:0,b:{session:createSession(),activities:createActivityState(),platform:freshPlatformState(),meta:freshSourceMetaState()}};
 c.owner=new SourceShopPurchaseClient({read:()=>({bundle:c.b,contextID:c.ctx}),write:b=>{if(c.fail)throw Error('quota');c.writes++;c.b=b;},requestID:()=>`Q${c.requests.length}`,now:()=> '2026-10-04T12:00:00Z',execute:async q=>{c.requests.push(q);return opts.execute?opts.execute(q):resp(q,opts.status);},notice:n=>c.notes.push(n),granted:()=>{c.shown++;if(opts.presentationThrow)throw Error('renderer');}});return c;
}
for(const [product,o] of Object.entries(SOURCE_PACKAGE_OFFERS))test(`purchase ${product} first grant/owned request guard/codec`,async()=>{
 const c=fixture();assert(await c.owner.request(product));assert.equal(c.b.session.diamonds,o.firstDiamonds);assert(c.b.meta.entitlements[o.entitlement]);assert.equal(c.b.platform.sequence,1);assert.equal(c.shown,1);assert(!await c.owner.request(product));assert.equal(c.requests.length,1);
 c.b={...c.b,session:deserializeSession(serializeSession(c.b.session)),meta:decodeSourceMetaState(serializeSourceMetaState(c.b.meta)),platform:decodePlatformState(JSON.stringify(c.b.platform))};assert(c.b.meta.entitlements[o.entitlement]);assert(c.b.platform.claims.includes('Q0'));
});
for(const status of ['failure','cancelled','unavailable'])test(`purchase ${status} grants no balance/rights/ledger`,async()=>{const c=fixture({status}),b=c.b;assert(!await c.owner.request('autoupgrade_pack'));assert.equal(c.b,b);assert.equal(c.writes,0);assert.equal(c.owner.pending,null);});
for(const field of ['id','purpose','kind','provider','onlineVerified'])test(`purchase mismatched ${field} rejected`,async()=>{const c=fixture({execute:q=>({...resp(q),[field]:field==='onlineVerified'?true:'wrong'})});assert(!await c.owner.request('autoupgrade_pack'));assert.equal(c.writes,0);});
test('save-failure retry rebases wallet and unrelated state, same receipt/provider call once',async()=>{const c=fixture(),old=c.b;c.fail=true;assert(!await c.owner.request('autoupgrade_pack'));assert.equal(c.b,old);assert(c.owner.saveFailed);assert.equal(c.shown,0);assert(!await c.owner.request('dia_pack'));assert(!c.owner.retrySave('dia_pack'));c.b={...c.b,session:{...c.b.session,diamonds:77},meta:{...c.b.meta,petCoin:9}};c.fail=false;assert(c.owner.retrySave('autoupgrade_pack'));assert.equal(c.b.session.diamonds,577);assert.equal(c.b.meta.petCoin,9);assert.equal(c.requests.length,1);assert.equal(c.writes,1);assert.equal(c.b.platform.claims.filter(x=>x==='Q0').length,1);assert(!c.owner.retrySave('autoupgrade_pack'));});
test('retry recomputes first-buy after another grant; never doubles a stale first-buy',async()=>{const product=contract.shop.offerings[0],c=fixture();c.fail=true;await c.owner.request(product.id);const other=fixture();await other.owner.request(product.id);c.b={...c.b,session:{...c.b.session,diamonds:40},meta:{...c.b.meta,shopFirstBuy:other.b.meta.shopFirstBuy}};c.fail=false;assert(c.owner.retrySave(product.id));assert.equal(c.b.session.diamonds,40+product.reward.amount);});
for(const product of contract.shop.offerings)test(`consumable ${product.id} source first-buy then regular`,async()=>{const c=fixture();assert(await c.owner.request(product.id));assert.equal(c.b.session.diamonds,product.reward.amount*product.firstPurchaseMultiplier);assert(await c.owner.request(product.id));assert.equal(c.b.session.diamonds,product.reward.amount*(product.firstPurchaseMultiplier+1));assert.equal(c.b.platform.sequence,2);});
test('request guards known products and field, before execute',async()=>{const c=fixture();for(const p of ['unknown','__proto__','remove_all_ads'])assert(!await c.owner.request(p));assert.equal(c.requests.length,0);c.b.session.mode='mine';assert.match(sourceShopPurchaseRequestGate(c.b,'autoupgrade_pack'),/普通/);assert(!await c.owner.request('autoupgrade_pack'));assert.equal(c.requests.length,0);});
test('double request only one provider call; current wallet consumed at callback, not captured snapshot',async()=>{const d=deferred(),c=fixture({execute:()=>d.promise}),a=c.owner.request('autoupgrade_pack');assert(!await c.owner.request('autoupgrade_pack'));c.b={...c.b,session:{...c.b.session,diamonds:11}};d.resolve(resp(c.requests[0]));assert(await a);assert.equal(c.b.session.diamonds,511);assert.equal(c.requests.length,1);});
test('context replacement and invalidate discard obsolete callback without clearing current pending',async()=>{const d=deferred(),e=deferred(),c=fixture({execute:q=>q.id==='Q0'?d.promise:e.promise}),a=c.owner.request('autoupgrade_pack');c.owner.invalidate();const b=c.owner.request('buff_pack');d.resolve(resp(c.requests[0]));assert(!await a);assert.equal(c.owner.pending.purpose,'buff_pack');e.resolve(resp(c.requests[1]));assert(await b);assert(!c.b.meta.entitlements.autoUpgradePack);assert(c.b.meta.entitlements.buffPack);});
test('replacement save context while pending or saveFailed grants nothing',async()=>{const d=deferred(),c=fixture({execute:()=>d.promise}),a=c.owner.request('autoupgrade_pack');c.ctx='B';d.resolve(resp(c.requests[0]));assert(!await a);assert.equal(c.writes,0);const r=fixture();r.fail=true;await r.owner.request('autoupgrade_pack');r.ctx='B';r.fail=false;assert(!r.owner.retrySave('autoupgrade_pack'));assert.equal(r.writes,0);assert.equal(r.owner.pending,null);});
test('receipt already in current ledger drops callback; native restored owned flag grants zero diamonds',async()=>{const d=deferred(),c=fixture({execute:()=>d.promise}),a=c.owner.request('autoupgrade_pack');c.b.platform.claims=['Q0'];d.resolve(resp(c.requests[0]));assert(!await a);assert.equal(c.writes,0);const e=deferred(),r=fixture({execute:()=>e.promise}),b=r.owner.request('autoupgrade_pack');r.b.meta.entitlements.autoUpgradePack=true;e.resolve(resp(r.requests[0]));assert(await b);assert.equal(r.b.session.diamonds,0);assert.equal(r.b.platform.sequence,1);});
test('provider exception and wallet overflow do not leave busy lock or partially publish',async()=>{const c=fixture({execute:()=>{throw Error('offline');}});assert(!await c.owner.request('autoupgrade_pack'));assert.equal(c.owner.pending,null);const r=fixture();r.b.session.diamonds=Number.MAX_SAFE_INTEGER;const b=r.b;assert(!await r.owner.request('autoupgrade_pack'));assert.equal(r.b,b);assert.equal(r.owner.pending,null);assert.equal(r.writes,0);});
test('presentation failure after commit cannot duplicate saved reward',async()=>{const c=fixture({presentationThrow:true});assert(await c.owner.request('autoupgrade_pack'));assert.equal(c.writes,1);assert.equal(c.b.session.diamonds,500);assert.equal(c.owner.pending,null);});
