import test from 'node:test';
import assert from 'node:assert/strict';
import {createSession,sourceGun} from '../session.ts';
import {createActivityState,claimDaily,claimMission,observeActivities,decodeActivityState,serializeActivityState,developerActivityExp,passView,claimPass,ACTIVITY_MISSIONS} from '../source-activities.ts';
test('seven sequential dates, no replay, rollback or unknown cycle',()=>{let s=createSession(),a=createActivityState();let total=0;for(let i=0;i<7;i++){const day=`2026-10-0${i+1}`,r=claimDaily(s,a,day);assert.equal(r.claimed,true);total+=[70,200,400,600,800,1000,1500][i];s=r.session;a=r.state;assert.equal(claimDaily(s,a,day).claimed,false);}assert.equal(s.diamonds,total);assert.equal(claimDaily(s,a,'2026-10-08').claimed,false);assert.equal(claimDaily(s,a,'2026-09-30').claimed,false);});
test('conservative legacy migration, strict decode and safe wallet',()=>{const a=createActivityState({dailyClaimed:true},'2026-10-01');assert.equal(a.dailyClaims,1);assert.equal(claimDaily(createSession(),a,'2026-10-01').claimed,false);assert.deepEqual(decodeActivityState(serializeActivityState(a)),a);for(const patch of [{dailyClaims:8},{passExp:NaN},{missionClaims:['mission-20']},{passClaims:[1]},{lastDailyDate:'2026-02-30'},{counters:{...a.counters,rebirth:-1}}])assert.throws(()=>decodeActivityState(JSON.stringify({...a,...patch})));assert.throws(()=>claimDaily({...createSession(),diamonds:Number.MAX_SAFE_INTEGER},createActivityState(),'2026-10-01'));});
test('observations only new H5 transitions, replay idempotency, no historic backfill',()=>{const p=createSession(),n={...p,events:[{type:'death',id:p.battle.targets[0].id,x:0,y:0},{type:'stageWon',stage:1}]};let a=observeActivities(createActivityState(),p,n);assert.equal(a.counters['tree-destroyed'],1);assert.equal(a.counters['stage-cleared'],1);assert.equal(observeActivities(a,p,n),a);assert.equal(observeActivities(a,n,n),a);a=observeActivities(a,n,{...n,events:[],rebirthCount:2});assert.equal(a.counters.rebirth,2);a=observeActivities(a,p,{...p,events:[],mode:'mine'});assert.equal(a.counters['mine-played'],1);assert.equal(observeActivities(a,p,{...p,events:[],mode:'mine'}),a);assert.equal(observeActivities(createActivityState(),{...p,mode:'challenge'},n).counters['tree-destroyed'],0);});
test('23 source thresholds, EXP stays EXP, VIP unavailable, claims persist',()=>{assert.equal(ACTIVITY_MISSIONS.length,23);let a=createActivityState();assert.equal(claimMission(a,'mission-0').claimed,false);a={...a,counters:{'tree-destroyed':100000,'stage-cleared':300,rebirth:6,'mine-played':2}};for(const m of ACTIVITY_MISSIONS){const r=claimMission(a,m.id);assert.equal(r.claimed,!m.requiresVip);a=r.state;assert.equal(claimMission(a,m.id).claimed,false);}assert.equal(a.passExp,200);assert.deepEqual(decodeActivityState(serializeActivityState(a)),a);});
test('pass 100 EXP levels, diamonds, duplicate gun grants, full inventory and ads',()=>{let a=createActivityState(),s=createSession();assert.equal(claimPass(s,a,0,{freeAdConfirmed:true}).claimed,false);assert.equal(developerActivityExp(a,false),a);a=developerActivityExp(a,true);assert.equal(passView(a).level,1);let r=claimPass(s,a,0,{freeAdConfirmed:true});assert.equal(r.claimed,true);s=r.session;a=r.state;assert.equal(s.diamonds,200);assert.equal(claimPass(s,a,0,{freeAdConfirmed:true}).claimed,false);a=developerActivityExp(a,true);r=claimPass(s,a,1,{freeAdConfirmed:true});s=r.session;a=r.state;assert.equal(s.diamonds,440);a=developerActivityExp(a,true);const full={...s,gunInventory:Array.from({length:16},()=>sourceGun(10))};r=claimPass(full,a,2,{freeAdConfirmed:true});assert.equal(r.reason,'inventory-full');assert.equal(r.session,full);assert.equal(r.state,a);assert.equal(r.claimed,false);s={...s,gunInventory:[sourceGun(10)]};r=claimPass(s,a,2,{freeAdConfirmed:true});assert.equal(r.claimed,true);assert.equal(r.session.gunInventory.length,2);assert.deepEqual(r.session.gunInventory.map(g=>g.id),['source-gun-10','source-gun-10']);assert.equal(r.session.diamonds,440);a=developerActivityExp(r.state,true);s=r.session;assert.deepEqual(decodeActivityState(serializeActivityState(a)),a);assert.equal(claimPass(s,a,3,{freeAdConfirmed:false}).reason,'ad-confirmation');r=claimPass(s,a,3,{freeAdConfirmed:true});assert.equal(r.claimed,true);assert.equal(r.session.diamonds,760);assert.equal(claimPass(s,{...a,passExp:2500},4,{freeAdConfirmed:true}).reason,'sequence');assert.equal(passView({...a,passExp:3000}).level,25);});
