/** Same-build test route registry. A present but invalid/empty route MUST stay isolated. */
import {SOURCE_HUNT_LIVE_QA_ROUTES} from "./hunt-qa-routes";
import {SOURCE_RAID_LIVE_QA_ROUTES} from "./raid-live-qa-routes";
export const SOURCE_QA_SCENARIOS = [
  ...SOURCE_HUNT_LIVE_QA_ROUTES,
  ...SOURCE_RAID_LIVE_QA_ROUTES,
  "offerwall-page","offerwall-shop","offerwall-hud","offerwall-locked","offerwall-pending",
  "freecash-page","freecash-hud","freecash-shop","freecash-buff","freecash-locked","freecash-over-hud","freecash-owned",
  "mine-speed",
  "mine-speed-auto",
  "mine-speed-empty",
  "mine-plus",
  "boss-plus","boss-plus-locked","boss-plus-active","hunt-plus","hunt-plus-locked","hunt-plus-active",
  "shop",
  "shop-owned",
  "shop-old-save",
  "mine-pack",
  "gun-daily","gun-daily-disabled","gun-daily-locked","gun-daily-full","gun-daily-used","gun-daily-remove-all","gun-daily-remove-forced","gun-daily-freecash",
  "auto-ad","auto-ad-used","auto-ad-active","auto-ad-permanent","auto-ad-off","auto-ad-remove-all","auto-ad-remove-forced","auto-ad-freecash",
  "adgun",
  "adgun-trigger",
  "adgun-disabled",
  "adgun-catalog",
  "adgun-full",
  "adgun-expire",
  "weekly",
  "weekly-hud",
  "weekly-locked",
  "weekly-vip-locked",
  "weekly-full",
  "weekly-cap",
  "plus-panel",
  "plus-active",
  "plus-expire",
  "plus-legacy",
  "diapig",
  "diapig-hud",
  "diapig-one",
  "diapig-both",
  "diapig-full",
  "stepup",
  "stepup-hud",
  "stepup-banner",
  "stepup-locked",
  "stepup-full",
  "stepup-expired",
  "stepup-complete",
  "gun-storage",
  "gun-storage-locked",
  "gun-storage-full",
  "gun-safe",
  "gun-safe-empty",
  "gun-safe-full",
  "gun-collection",
  "skin-list",
  "skin-detail",
  "skin-empty",
  "skin-owned",
  "raid-panel",
  "raid-empty",
  "raid-locked",
  "raid-ad",
  "raid-iap",
  "raid-used",
  "star-slots",
  "star-upgrade",
  "star-pity",
  "star-empty",
  "star-max",
  "star-locked",
  "challenge-3",
  "challenge-victory",
  "challenge-victory-auto",
  "challenge-freecash",
  "challenge-sweep",
  "challenge-sweep-auto",
  "challenge-sweep-low",
  "challenge-auto",
  "challenge-fight",
  "challenge-defeat",
  "upgrade-17",
  "entry",
  "third-stage",
  "third-layout",
  "three-cats",
  "upgrade-49",
  "upgrade-50",
  "upgrade-51",
  "last-gun",
  "eight-aim",
  "mine",
  "mine-result",
  "mine-result-freecash",
  "mine-sweep-result",
  "mine-result-auto",
  "rebirth",
  "permanent",
  "special-guns",
  "gun-drag",
  "gun-auto",
  "gun-auto-shop",
  "gun-auto-expire",
  "fish-panel",
  "boss-result-freecash",
  "boss-panel",
  "boss-battle",
  "boss-bonus",
  "boss-reward","boss-reward-plus","boss-reward-auto","boss-reward-save-failure",
  "pet-panel",
  "pet-drag",
  "pet-auto",
  "pet-auto-shop",
  "pet-auto-expire",
  "pet-info",
  "pet-draw-info",
  "hunt-panel",
  "hunt-client",
  "hunt-client-defeat",
  "hunt-client-locked",
  "hunt-sweep",
  "hunt-sweep-result",
  "hunt-sweep-result-auto",
  "hunt-sweep-result-freecash",
  "late-content",
  "prism-shop",
  "prism-cooldown",
  "prism-overflow",
  "relic-panel",
  "relic-upgrade",
  "relic-boundary",
  "relic-empty",
  "relic-consumers",
  "adventure-panel",
  "adventure-dispatch",
  "adventure-finish",
  "adventure-locked",
  "buff-panel",
  "pass-scroll",
  "pass-initial", "pass-later", "pass-core", "pass-next", "pass-provider", "pass-full", "pass-final", "pass-final-vip",
  "challenge-defeat-freecash"
] as const;
export type SourceQAScenario = typeof SOURCE_QA_SCENARIOS[number];
const known = new Set<string>(SOURCE_QA_SCENARIOS);
export function isSourceQAScenario(value: unknown): value is SourceQAScenario {
  return typeof value === 'string' && known.has(value);
}
export type SourceQARoute = {isolated:false; scenario:null; error:null} |
  {isolated:true; scenario:SourceQAScenario|null; error:string|null};
export function resolveSourceQARoute(search:string):SourceQARoute {
  const params=new URLSearchParams(search);
  if(!params.has('qa'))return {isolated:false,scenario:null,error:null};
  const name=params.get('qa');
  return isSourceQAScenario(name)?{isolated:true,scenario:name,error:null}:
    {isolated:true,scenario:null,error:`未知或空测试场景：${name||'(空)'}；普通存档未读取、未写入`};
}
export interface SourceQAStorage {getItem(key:string):string|null;setItem(key:string,value:string):void;}
/** Also protects developer transitions from a normal route into a fixture. Never seeds QA from player data. */
export function createSourceQAStorage(normal:SourceQAStorage,initiallyIsolated:boolean) {
  let isolated=initiallyIsolated;
  const data=new Map<string,string>();
  return {
    getItem(key:string){return isolated?(data.get(key)??null):normal.getItem(key);},
    setItem(key:string,value:string){if(isolated)data.set(key,value);else normal.setItem(key,value);},
    isolate(){isolated=true;data.clear();},
    get isolated(){return isolated;},
  };
}
