import {SourceRaidMissionClient} from './raid-mission-client';
import {createSourceRaidMissionPanel,type SourceRaidMissionPanelView} from './source-raid-mission-panel';
import {freshSourceRaidMission,sourceRaidMissionRefresh} from './r6-raid-mission';
/** Independent mode5 GUI fixture: memory-only codec, visible test clock and
 * local provider. Does not import main/start ordinary combat/read ordinary storage. */
import {Application,Assets,Texture} from 'pixi.js';
import hudData from './data/source-raid-hud.json';
import guns from './data/guns.json';
import {SourceRaidClientOwner} from './raid-client-owner';
import {SourceRaidCatClientScene} from './raid-cat-client-scene';
import {SourceRaidSceneView,RAID_SCENE_LIMITATIONS} from './raid-scene-view';
import {createSession,sourceGun,sourceGunID,serializeSession,deserializeSession} from './session';
import {freshSourceMetaState,serializeSourceMetaState,decodeSourceMetaState,type SourceMetaBundle} from './source-meta-runtime';
import {createActivityState,serializeActivityState,decodeActivityState} from './source-activities';
import {freshPlatformState,decodePlatformState} from './local-platform';
import {createSourceUiView,loadSourceUiFonts,type SourceUiTree,type SourceUiView} from './source-ui';
import {sourceUiTree} from './source-ui';
import {createSourceRaidPanel,sourceRaidAssetURLs,type SourceRaidPanelView} from './source-raid-panel';
import {createSourceRaidStarPigPanel,type SourceRaidStarPigPanelView} from './source-raid-star-pig-panel';
import {sourceRaidStarPigView,sourceRaidStarPigSeason,freshSourceRaidStarPig} from './r6-raid-star-pig';
import {SourceRaidHelperClient} from './raid-helper-client';
import {createSourceRaidHelperPanel,type SourceRaidHelperPanelView} from './source-raid-helper-panel';
import {sourceRaidHelperActive} from './r6-raid-helper';
import {SourceRaidStarPigClient} from './raid-star-pig-client';
import {sourceRaidSeason,sourceRaidTickets,sourceRaidAutoSelect,sourceRaidSelect,sourceRaidWeakType,type SourceRaidSelection,type SourceRaidGunRef} from './r6-raid';
import {sourceWeekOffset} from './r6-weekly';
import {createLocalMineTime} from './mine-time';
import {createLocalRewardProvider,type SourceProviderStatus} from './r6-reward-provider';
import {bindSourceHuntMovementStats} from './hunt-movement-binding';
import {sourceRelicTotals} from './r6-relic';
import {sourceRaidHUDCurrency} from './raid-hud-state';
const HUD='/Canvas/SafeArea/Raid_UI',hudTree=hudData as unknown as SourceUiTree;
const FIXTURE_DATE=new Date(2026,9,3,12);let qaDate=new Date(FIXTURE_DATE);const time=createLocalMineTime(()=>qaDate);
function fixture(route:string):SourceMetaBundle{
 const ids=route.endsWith('-holes')?[30,null,24]:[30,24,29];
 const session={...createSession(61003),historicMax:390,starGem:0,equippedGuns:ids.map((id,i)=>id===null?null:{...sourceGun(id),uid:`qa-raid-gun-${i}`}),bossSlotLevels:[0,0,0] as [number,number,number]};
 const meta=freshSourceMetaState();meta.raid=sourceRaidTickets(sourceRaidSeason(meta.raid,qaDate),time);
 meta.raidStarPig=sourceRaidStarPigSeason(freshSourceRaidStarPig(),meta.raid.seasonIndex);
 if(route.startsWith('raid-live-star-pig-')){const lv=route.endsWith('lv2')?2:route.endsWith('lv3')||route.endsWith('soldout')?3:1;const full=!route.endsWith('empty')&&!route.endsWith('soldout');meta.raidStarPig={...meta.raidStarPig,lv,gem:full?[660,1500,2500][lv-1]:0,purchaseCount:route.endsWith('soldout')?1:0};}
 if(route.startsWith('raid-live-helper-')){session.bossSlotLevels=[3,1,5];if(!route.endsWith('-unowned'))meta.raid.helperSeasonIndex=meta.raid.seasonIndex-(route.endsWith('-expired')?1:0);}
 if(route.startsWith('raid-live-mission-')){meta.raid.tryCount=route.endsWith('-empty')?0:7;meta.raid.bestLevel=route.endsWith('-empty')?0:30;meta.raidMission=sourceRaidMissionRefresh(meta.raidMission!,meta.raid);if(route.endsWith('-owned'))meta.raidMission.ticketPurchased=true;}
 if(route==='raid-live-ad')meta.raid={...meta.raid,freeUseCount:2};
 if(route==='raid-live-purchase')meta.raid={...meta.raid,freeUseCount:2,adUsed:true};
 return {session,meta,activities:createActivityState(undefined,'2026-10-03'),platform:{...freshPlatformState(),developerEnabled:true}};
}
export async function startRaidLiveQA(route:string):Promise<void>{
 const page=document.getElementById('game')!,style=document.createElement('style');
 style.textContent=`*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#242226;font-family:system-ui;color:white}#game{width:100%;height:100%}.raid-stage{position:absolute;inset:0}.raid-stage canvas{display:block;width:100%;height:100%;touch-action:none}.raid-controls{position:absolute;z-index:4;left:auto;right:8px;width:min(300px,calc(100vw - 82px));bottom:6px;background:#15171bea;border:1px solid #b4a8c8;border-radius:8px;padding:6px;font-size:11px;line-height:1.4;max-height:36vh;overflow:auto}.raid-controls:has(details[open]){left:8px;width:calc(100vw - 16px)}.raid-controls strong{color:#ffc774}.raid-controls button,.raid-controls select{font:inherit;margin:3px 2px;padding:5px 7px;min-height:30px;border:1px solid #69745c;border-radius:4px;background:#d5ddc6;color:#1a2515}.raid-controls button:disabled{opacity:.5}.raid-controls a{color:#c8eab0}.raid-controls pre{white-space:pre-wrap;margin:3px 0}.raid-message{color:#ffe891}.raid-stick{position:absolute;z-index:3;top:64%;left:6%;width:86px;height:86px;border:1px solid #fff8;border-radius:50%;background:#21282180;touch-action:none;display:grid;place-items:center;color:#fff8;font-size:12px}.raid-mask{position:absolute;inset:0;z-index:2;display:none;place-items:center;background:#18181fe8;text-align:center;padding:25px;color:#ffdfb0;pointer-events:auto}`;
 document.head.append(style);page.innerHTML=`<div class="raid-stage"></div><div class="raid-mask"></div><div class="raid-stick">拖动方向</div><section class="raid-controls"><strong>第六轮 · 突袭实时隔离夹具 ${route}</strong><br>原图／骨骼挂点／逐弹入账。普通档零读写；非原机等价。<details><summary>测试控制与状态（展开）</summary><div><button id="raid-start">进入源突袭</button><button id="raid-exit">退出／返回入口</button><button id="raid-pause">暂停测试</button><button id="raid-eco">省电：关</button><button id="raid-reset">重置夹具</button><button id="raid-roundtrip">保存重载测试档</button><button id="raid-next-week">夹具下一周</button><a href="/qa.html">全功能选择页</a></div><label>测试时钟 <select id="raid-rate"><option value="1">1×</option><option value="5">5× H5子帧</option><option value="10">10× H5子帧</option></select></label> <label>本地 provider <select id="raid-provider"><option value="success">成功</option><option value="failure">失败</option><option value="cancelled">取消</option><option value="unavailable">未连接</option><option value="delayed-success">延迟成功 2s</option></select></label><div class="raid-message"></div><pre class="raid-state"></pre><details><summary>证明缺口与夹具标记</summary><div class="raid-limits"></div></details></details></section>`;
 page.querySelector('.raid-limits')!.textContent=`固定测试民用日期2026-10-03 12:00、源枪30/24/29、零星级/宠物/遗物增益、本地组件ID作测试seed。${RAID_SCENE_LIMITATIONS.join(' ')}`;
 if(route.startsWith('raid-live-star-pig-'))page.querySelector('.raid-controls strong')!.textContent+=` · 存钱罐${route.split('-').at(-1)}注入夹具`;
 const app=new Application({width:innerWidth,height:innerHeight,resolution:Math.min(devicePixelRatio,2),backgroundColor:0x302e35,antialias:true,autoDensity:true});page.querySelector('.raid-stage')!.appendChild(app.view as HTMLCanvasElement);
 const urls=[...new Set([...fixture(route).session.equippedGuns.filter(g=>g!==null).map(g=>guns.guns[sourceGunID(g!)].spriteURL),...hudTree.nodes.flatMap(n=>n.components.map(c=>c.data?.textureURL??hudTree.sprites[c.data?.spriteKey]?.url).filter((v):v is string=>!!v)),...sourceRaidAssetURLs,...sourceUiTree.nodes.filter(n=>n.path.startsWith('/Canvas/Contents_UI/Raid_UI')).flatMap(n=>n.components.map(c=>c.data?.textureURL??sourceUiTree.sprites[c.data?.spriteKey]?.url).filter((v):v is string=>!!v))])];
 const textures:Record<string,Texture>={};await Promise.all([loadSourceUiFonts(),...urls.map(async url=>{textures[url]=await Assets.load<Texture>(url);})]);
 let bundle=fixture(route),owner:SourceRaidClientOwner|null=null,view:SourceRaidSceneView|null=null,hud:SourceUiView|null=null,panel:SourceRaidPanelView|null=null,pigPanel:SourceRaidStarPigPanelView|null=null;
 let pigOpen=route.startsWith('raid-live-star-pig-'),helperOpen=route.startsWith('raid-live-helper-');let helperPanel:SourceRaidHelperPanelView|null=null;
 let missionOpen=route.startsWith('raid-live-mission-'),ticketOpen=false;let missionPanel:SourceRaidMissionPanelView|null=null;
 let selection=sourceRaidAutoSelect(bundle.session,sourceRaidWeakType(bundle.meta.raid.seasonIndex)),selectingSlot:number|null=null;
 let paused=false,eco=false,generation=0,rate=1,providerOutcome:SourceProviderStatus|'delayed-success'='success',notice='原入口准备完毕；场景资源在入场请求后准备，准备期间不扣次数。';
 let saveCount=0,encodedSave:string|null=null,finalHits=0,finalAttacks=0,finalFrames=0,finalRenders=0;
 const history:{kind:string;phase:string;reason?:string;score?:number;starGem?:number;id?:string}[]=[];
 let joystick={x:0,y:0},pointer:number|null=null,origin={x:0,y:0};const keys=new Set<string>();
 const encode=(b:SourceMetaBundle)=>JSON.stringify({session:JSON.parse(serializeSession(b.session)),meta:JSON.parse(serializeSourceMetaState(b.meta)),activities:JSON.parse(serializeActivityState(b.activities)),platform:b.platform});
 const save=()=>{encodedSave=encode(bundle);saveCount++;};
 function closeHud(){hud?.destroy();hud=null;}
 function discard(){generation++;pigClient.invalidate();helperClient.invalidate();missionClient.invalidate();missionPanel?.destroy();missionPanel=null;missionOpen=false;ticketOpen=false;helperPanel?.destroy();helperPanel=null;helperOpen=false;pigPanel?.destroy();pigPanel=null;pigOpen=false;if(owner){finalHits=owner.hitCount;finalFrames=owner.frameCount;finalRenders=owner.renderCount;}if(view)finalAttacks=view.attackCount;owner?.cancel();owner=null;view=null;closeHud();joystick={x:0,y:0};}
 function updateHUD(){if(!owner||!hud)return;const host=owner.host,enemy=host.boss.enemy;
  hud.setText(HUD+'/Time_Slider/Time_txt',`${Math.max(0,Math.ceil(host.remainingSeconds))}`);hud.setFill(HUD+'/Time_Slider/Fill',Math.max(0,host.remainingSeconds/host.maximumSeconds));
  hud.setText(HUD+'/HP_Slider/HP_txt',`${enemy.health.format(3)} / ${enemy.maxHealth.format(3)}`);hud.setFill(HUD+'/HP_Slider/Fill',enemy.health.fractionOf(enemy.maxHealth));
  hud.setText(HUD+'/HP_Slider/Score_txt',`${host.score}`);hud.setText(HUD+'/HighScore_txt',`${bundle.meta.raid.bestLevel}`);const currency=sourceRaidHUDCurrency(bundle.session);hud.setText(HUD+'/Currency/Dia/Price_txt',currency.diamonds);hud.setText(HUD+'/Currency/Money/Price_txt',currency.money);
 }
 function panelState(){return {session:bundle.session,state:bundle.meta.raid,selection,selectingSlot,nowUTC:qaDate.getTime(),notice,ready:true,pig:bundle.meta.raidStarPig,mission:bundle.meta.raidMission};}
 function updatePanel(){const show=!owner;
  if(!show){panel?.destroy();panel=null;return;}
  if(panel){panel.sync(panelState());updatePigPanel();updateHelperPanel();updateMissionPanel();return;}
  panel=createSourceRaidPanel({...panelState(),textures,viewport:{width:innerWidth,height:innerHeight},action:(action,payload)=>{
   if(action==='raid-mission'){missionOpen=true;ticketOpen=false;updateMissionPanel();}else if(action==='raid-helper'){helperOpen=true;updateHelperPanel();}else if(action==='raid-source-orphan'){notice='原助手星级按钮事件目标为空；使用三槽最小星级，无第四强化槽（H5说明）';}else if(action==='raid-star-pig'){pigOpen=true;updatePigPanel();}else if(action==='raid-enter')void enter();else if(action==='raid-slot'){selectingSlot=Number(payload);updatePanel();}else if(action==='raid-select-close'){selectingSlot=null;updatePanel();}else if(action==='raid-select'&&selectingSlot!==null){const r=sourceRaidSelect(bundle.session,selection,selectingSlot,payload as SourceRaidGunRef);selection=r.selection;notice=r.reason??'源选枪已更新';selectingSlot=null;updatePanel();}else if(action==='raid-unselect'){selection=selection.map((s,i)=>i===Number(payload)?null:s);updatePanel();}else if(action==='raid-auto-select'){selection=sourceRaidAutoSelect(bundle.session,sourceRaidWeakType(bundle.meta.raid.seasonIndex));updatePanel();}else if(action==='raid-close'){selectingSlot=null;notice='原菜单返回上下文已保留；本页没有普通战斗，可返回全功能选择页。';updatePanel();}else notice=`源动作 ${action} 尚未在本隔离页闭合（${String(payload??'')}）；不伪造服务成功。`; renderState();}});app.stage.addChild(panel.root);updatePigPanel();updateHelperPanel();updateMissionPanel();
 }
 function missionPanelState(){return {state:bundle.meta.raidMission??freshSourceRaidMission(),raid:bundle.meta.raid,nowUTC:qaDate.getTime(),ticketOpen,pending:missionClient.pending,notice};}
 function updateMissionPanel(){if(!missionOpen||owner){missionPanel?.destroy();missionPanel=null;return;}if(missionPanel){missionPanel.sync(missionPanelState());return;}
  missionPanel=createSourceRaidMissionPanel({...missionPanelState(),textures,viewport:{width:innerWidth,height:innerHeight},action:(action,payload)=>{if(action==='raid-mission-close'){missionOpen=false;ticketOpen=false;}else if(action==='raid-mission-ticket-close')ticketOpen=false;else if(action==='raid-mission-claim')missionClient.claim(Number(payload));else if(action==='raid-mission-reclaim')missionClient.claim(Number(payload),true);else if(action==='raid-mission-purchase')void purchaseMission();else notice='原锁定／开发测试对象：没有可领取奖励，不开启源隐藏测试按钮';updatePanel();renderState();}});app.stage.addChild(missionPanel.root);
 }
 const missionClient=new SourceRaidMissionClient({
  read:()=>({bundle,contextID:`qa:${generation}`}),requestID:()=>`qa-mission:${crypto.randomUUID()}`,
  write(next){const encoded=encode(next);bundle=next;encodedSave=encoded;saveCount++;history.push({kind:'mission-save',phase:'idle',starGem:bundle.session.starGem});},
  async execute(request){const outcome=providerOutcome;history.push({kind:'mission-provider-request',phase:'idle',id:request.id});if(outcome==='delayed-success')await new Promise(resolve=>setTimeout(resolve,2000));const r=await createLocalRewardProvider(outcome!=='unavailable',outcome==='failure'||outcome==='cancelled'?outcome:'success').execute(request);history.push({kind:'mission-provider-'+r.status,phase:'idle',id:request.id});return r;},
  notice(message){notice=message;updatePanel();renderState();},ticketPopup(){ticketOpen=true;updatePanel();}
 });
 async function purchaseMission(){const ok=missionClient.saveFailed?missionClient.retrySave():await missionClient.purchase();if(ok)ticketOpen=false;updatePanel();renderState();}
 function helperPanelState(){return {state:bundle.meta.raid,weakType:sourceRaidWeakType(bundle.meta.raid.seasonIndex),historicMax:bundle.session.historicMax,pending:helperClient.pending,notice};}
 function updateHelperPanel(){if(!helperOpen||owner){helperPanel?.destroy();helperPanel=null;return;}if(helperPanel){helperPanel.sync(helperPanelState());return;}
  helperPanel=createSourceRaidHelperPanel({...helperPanelState(),textures,viewport:{width:innerWidth,height:innerHeight},action:action=>{if(action==='raid-helper-close'){helperOpen=false;updatePanel();}else if(action==='raid-helper-purchase')void purchaseHelper();renderState();}});app.stage.addChild(helperPanel.root);}
 const helperClient=new SourceRaidHelperClient({
  read:()=>({state:bundle.meta.raid,historicMax:bundle.session.historicMax,contextID:`qa:${generation}`}),requestID:()=>`qa-helper:${crypto.randomUUID()}`,
  write(state){const next={...bundle,meta:{...bundle.meta,raid:state}},encoded=encode(next);bundle=next;encodedSave=encoded;saveCount++;history.push({kind:'helper-save',phase:'idle'});},
  async execute(request){const outcome=providerOutcome;history.push({kind:'helper-provider-request',phase:'idle',id:request.id});if(outcome==='delayed-success')await new Promise(resolve=>setTimeout(resolve,2000));const r=await createLocalRewardProvider(outcome!=='unavailable',outcome==='delayed-success'||outcome==='unavailable'?'success':outcome).execute(request);history.push({kind:`helper-provider-${r.status}`,phase:'idle',id:r.id});return r;},
  notice(message){notice=message;updateHelperPanel();renderState();}
 });
 async function purchaseHelper(){const ok=helperClient.saveFailed?helperClient.retrySave():await helperClient.purchase();if(ok)helperOpen=false;updatePanel();renderState();}
 function pigPanelState(){return {state:bundle.meta.raidStarPig??freshSourceRaidStarPig(),historicMax:bundle.session.historicMax,pending:pigClient.pending,notice};}
 function updatePigPanel(){if(!pigOpen||owner){pigPanel?.destroy();pigPanel=null;return;}if(pigPanel){pigPanel.sync(pigPanelState());return;}pigPanel=createSourceRaidStarPigPanel({...pigPanelState(),textures,viewport:{width:innerWidth,height:innerHeight},action:action=>{if(action==='raid-star-pig-close'){pigOpen=false;updatePigPanel();updatePanel();}else if(action==='raid-star-pig-purchase')void purchasePig();renderState();}});app.stage.addChild(pigPanel.root);}
 const pigClient=new SourceRaidStarPigClient({
  read:()=>({state:bundle.meta.raidStarPig??freshSourceRaidStarPig(),starGem:bundle.session.starGem??0,historicMax:bundle.session.historicMax,contextID:`qa:${generation}`}),
  requestID:()=>`qa-raid-pig:${crypto.randomUUID()}`,
  write(state,starGem){const next={...bundle,session:{...bundle.session,starGem},meta:{...bundle.meta,raidStarPig:state}},encoded=encode(next);bundle=next;encodedSave=encoded;saveCount++;history.push({kind:'save',phase:'idle',reason:'star-pig',starGem});},
  async execute(request){const outcome=providerOutcome;history.push({kind:'pig-provider-request',phase:'idle',id:request.id});if(outcome==='delayed-success')await new Promise(resolve=>setTimeout(resolve,2000));const r=await createLocalRewardProvider(outcome!=='unavailable',outcome==='delayed-success'||outcome==='unavailable'?'success':outcome).execute(request);history.push({kind:`pig-provider-${r.status}`,phase:'idle',id:r.id});return r;},
  notice(message){notice=message;updatePigPanel();renderState();}
 });
 async function purchasePig(){if(pigClient.saveFailed)pigClient.retrySave();else await pigClient.purchase();updatePanel();renderState();}
 async function enter(){if(owner||pigClient.pending||pigOpen||helperClient.pending||helperOpen||missionClient.pending||missionOpen)return;const token=++generation,id=`qa-raid:${route}:${token}`;
  try{
   const client:SourceRaidClientOwner=new SourceRaidClientOwner(id,selection,{read:()=>bundle,current:()=>generation===token&&owner===client,
    write(next,reason){const encoded=encode(next);bundle=next;encodedSave=encoded;saveCount++;history.push({kind:'save',phase:client.phase,reason,score:client.host.score,starGem:bundle.session.starGem});},
    scene(host,s){const world=new SourceRaidSceneView(host,bundle,s,sourceWeekOffset(qaDate),innerWidth,innerHeight);view=world;app.stage.addChild(world.root);
     return new SourceRaidCatClientScene(host,s,{read:()=>bundle,prepare:()=>world.prepare(),bindCats:c=>world.bindCats(c),movementStats:()=>bindSourceHuntMovementStats(bundle.meta.pet,sourceRelicTotals(bundle.meta.relic).moveSpeedValue),followSettings:()=>world.followSettings(),adapter:()=>world.adapter(),consume:(e,f,a,dt)=>world.consume(e,f,a,dt),render:(dt,c)=>world.render(dt,c),destroy:()=>world.destroy(),setPresentationEnabled:e=>world.setPresentationEnabled(e)});},
    async execute(request){const outcome=providerOutcome;history.push({kind:'provider-request',phase:client.phase,id:request.id});if(outcome==='delayed-success')await new Promise(resolve=>setTimeout(resolve,2000));const r=await createLocalRewardProvider(outcome!=='unavailable',outcome==='delayed-success'||outcome==='unavailable'?'success':outcome).execute(request);history.push({kind:`provider-${r.status}`,phase:client.phase,id:r.id});return r;},notice:text=>{notice=text;},events:events=>{for(const e of events){history.push({kind:e.kind==='battle'?e.event.kind:e.kind,phase:client.phase,...(e.kind==='battle'&&e.event.kind==='end'?{score:e.event.result.score,starGem:e.event.result.starGem}:{})});if(e.kind==='phase'&&e.phase==='playing')notice='源Start已提交；同一时钟推进Cat／弹丸／60秒计时。';if(e.kind==='phase'&&e.phase==='ended')notice=`源计时结束：真实逐弹分数 ${client.host.score}，星宝石已保存一次。`;}renderState();}});
   owner=client;updatePanel();notice='原场景准备中；次数未扣、战斗和计时未启动。';renderState();
   const admitted=await client.start();if(token!==generation||owner!==client)return;
   if(!admitted){discard();updatePanel();renderState();return;}
   hud=createSourceUiView({tree:hudTree,roots:[HUD],textures,viewport:{width:innerWidth,height:innerHeight},active:{[HUD]:true,'/Canvas':true,'/Canvas/SafeArea':true}});hud.bindAction(HUD+'/Exit_Btn',()=>{if(client.exit())notice='原退出等待1.5s+0.2s；未结束不发奖、不退次数。';renderState();});app.stage.addChild(hud.root);updateHUD();notice='资源已提交；源入场等待2s，随后才Start并推进逐弹战斗。';renderState();
  }catch(error){notice=`突袭准备失败：${String(error)}；不产生假结算`;discard();updatePanel();renderState();}
 }
 const state=()=>({route,isolated:true,onlineConnected:false,fixture:{date:qaDate.toISOString(),rate,provider:'local-test',providerOutcome,seedIdentity:view?.rng.identity??'local-test-xorshift32',guns:bundle.session.equippedGuns.map(g=>g?.id??null),star:bundle.session.bossSlotLevels},phase:owner?.phase??'idle',ready:owner?.ready??false,pending:owner?.pending??false,paused,eco,notice,raid:bundle.meta.raid,starGem:bundle.session.starGem??0,pig:bundle.meta.raidStarPig,pigView:sourceRaidStarPigView(bundle.meta.raidStarPig??freshSourceRaidStarPig()),missionOpen,ticketOpen,missionPending:missionClient.pending,missionSaveFailed:missionClient.saveFailed,mission:bundle.meta.raidMission,missionInstance:missionPanel?.instanceId,missionScroll:missionPanel?.captureScroll(),helperOpen,helperActive:sourceRaidHelperActive(bundle.meta.raid),helperPending:helperClient.pending,helperSaveFailed:helperClient.saveFailed,helperAttacks:view?.attackByCat.get(136810)??0,helperHits:view?.hitsByCat.get(136810)??0,pigOpen,pigPending:pigClient.pending,pigSaveFailed:pigClient.saveFailed,pigTexts:pigPanel?Object.fromEntries([...pigPanel.texts].map(([id,t])=>[id,t.text])):{},selection,remaining:owner?.host.remainingSeconds??null,wait:owner?.waitSeconds??0,score:owner?.host.score??bundle.meta.raid.bestLevel,saveCount,hitCount:owner?.hitCount??finalHits,attackCount:view?.attackCount??finalAttacks,frames:owner?.frameCount??finalFrames,renders:owner?.renderCount??finalRenders,projectiles:owner?.host.projectiles.activeCount??0,projectilePresentation:view?{active:view.projectilePresentation.active.size,retired:view.projectilePresentation.retired.size,births:view.projectilePresentation.births}:null,camera:view?.ready?view.projectionState():null,cats:owner?.scene instanceof SourceRaidCatClientScene?owner.scene.cats?.cats.map(c=>({componentID:c.componentID,role:c.role,gun:c.gun.gunNum,star:c.gun.starLevel,selectionSlot:c.selectionSlot,position:c.movement.position,screen:view?.project(c.movement.position)})):null,failures:{simulation:owner?.simulationFailure,presentation:owner?.presentationFailure,save:owner?.saveFailure},history:[...history],layouts:{hud:hud?[...hud.layout.values()]:[],panel:panel?[...panel.layout.values()]:[],pig:pigPanel?[...pigPanel.layout.values()]:[],mission:missionPanel?[...missionPanel.layout.values()].filter(n=>missionPanel!.boundActions.has(n.id)).map(n=>({id:n.id,x:n.x,y:n.y,width:n.width,height:n.height,active:n.active})):[],helper:helperPanel?[...helperPanel.layout.values()]:[]},hudCurrency:hud?{diamonds:hud.getText(HUD+'/Currency/Dia/Price_txt')?.text,money:hud.getText(HUD+'/Currency/Money/Price_txt')?.text}:null,maskVisible:(page.querySelector('.raid-mask') as HTMLElement).style.display!=='none',diagnostics:{hud:hud?.diagnostics??[],panel:panel?.diagnostics??[],mission:missionPanel?.diagnostics??[],pig:pigPanel?.diagnostics??[],helper:helperPanel?.diagnostics??[]},limitations:RAID_SCENE_LIMITATIONS});
 function renderState(){const s=state();page.querySelector('.raid-message')!.textContent=notice;page.querySelector('.raid-state')!.textContent=`${s.phase} · 分数 ${s.score} · 剩余 ${s.remaining?.toFixed(2)??'-'}s · 星宝石 ${s.starGem}\n射击 ${s.attackCount} / 逐弹命中 ${s.hitCount} / 活跃弹 ${s.projectiles}\n计算帧 ${s.frames} / 绘制帧 ${s.renders} · 本地保存 ${s.saveCount}\n免费已用 ${s.raid.freeUseCount} / 广告已用 ${Number(s.raid.adUsed)} / Start ${s.raid.tryCount}`;
  (page.querySelector('#raid-start') as HTMLButtonElement).disabled=!!owner;(page.querySelector('#raid-exit') as HTMLButtonElement).disabled=!owner||!['playing','ended'].includes(owner.phase);
  (page.querySelector('.raid-stick') as HTMLElement).style.display=owner?.phase==='playing'&&!paused?'grid':'none';
  const mask=page.querySelector('.raid-mask') as HTMLElement,masked=owner&&['preparing','provider','enter-loading','exit-mask-wait'].includes(owner.phase);mask.style.display=masked?'grid':'none';mask.textContent=owner?.phase==='provider'?'明示本地测试 provider 等待中；无真实广告或支付':owner?.phase==='enter-loading'?'源突袭入场等待 2s；场景已准备，战斗尚未开始':'准备／退出原场景；不双推进时钟';
 }
 const click=(id:string,fn:()=>void)=>page.querySelector(id)!.addEventListener('click',fn);
 click('#raid-start',()=>void enter());click('#raid-exit',()=>{if(owner?.exit()){notice='退出未结束的源战斗，不发奖、不退款。';renderState();}});
 click('#raid-pause',()=>{paused=!paused;joystick={x:0,y:0};keys.clear();renderState();});
 click('#raid-eco',()=>{eco=!eco;owner?.scene.setPresentationEnabled?.(!eco);(page.querySelector('#raid-eco') as HTMLButtonElement).textContent=`省电：${eco?'开':'关'}`;renderState();});
 click('#raid-reset',()=>{discard();panel?.destroy();panel=null;qaDate=new Date(FIXTURE_DATE);bundle=fixture(route);missionOpen=route.startsWith('raid-live-mission-');ticketOpen=false;helperOpen=route.startsWith('raid-live-helper-');pigOpen=route.startsWith('raid-live-star-pig-');selection=sourceRaidAutoSelect(bundle.session,sourceRaidWeakType(bundle.meta.raid.seasonIndex));selectingSlot=null;encodedSave=null;saveCount=0;finalHits=0;finalAttacks=0;finalFrames=0;finalRenders=0;history.length=0;paused=false;notice='独立夹具已重置；普通存档零读写。';updatePanel();renderState();});
 click('#raid-roundtrip',()=>{save();const raw=JSON.parse(encodedSave!);discard();bundle={session:deserializeSession(JSON.stringify(raw.session)),meta:decodeSourceMetaState(JSON.stringify(raw.meta)),activities:decodeActivityState(JSON.stringify(raw.activities)),platform:decodePlatformState(JSON.stringify(raw.platform))};selection=sourceRaidAutoSelect(bundle.session,sourceRaidWeakType(bundle.meta.raid.seasonIndex));notice='隔离存档重载：次数／高分／星宝石保留；运行与选枪不保存，不补发。';updatePanel();renderState();});
 click('#raid-next-week',()=>{if(owner){notice='先退出战斗再推进测试周历';renderState();return;}qaDate=new Date(qaDate.getTime()+7*86400000);bundle={...bundle,meta:{...bundle.meta,raid:sourceRaidTickets(sourceRaidSeason(bundle.meta.raid,qaDate),time),raidMission:sourceRaidMissionRefresh(bundle.meta.raidMission??freshSourceRaidMission(),sourceRaidSeason(bundle.meta.raid,qaDate)),raidStarPig:sourceRaidStarPigSeason(bundle.meta.raidStarPig??freshSourceRaidStarPig(),sourceRaidSeason(bundle.meta.raid,qaDate).seasonIndex)}};save();notice='测试周历已推进；旧助手权益保留历史字段但本周失效';updatePanel();renderState();});
 page.querySelector('#raid-rate')!.addEventListener('change',e=>{rate=Number((e.target as HTMLSelectElement).value);renderState();});page.querySelector('#raid-provider')!.addEventListener('change',e=>{providerOutcome=(e.target as HTMLSelectElement).value as typeof providerOutcome;renderState();});
 const stick=page.querySelector('.raid-stick') as HTMLElement;stick.addEventListener('pointerdown',e=>{if(pointer!==null)return;pointer=e.pointerId;origin={x:e.clientX,y:e.clientY};stick.setPointerCapture(pointer);});stick.addEventListener('pointermove',e=>{if(pointer!==e.pointerId)return;let x=(e.clientX-origin.x)/34,y=-(e.clientY-origin.y)/34;const d=Math.hypot(x,y);if(d>1){x/=d;y/=d;}joystick={x,y};});const release=()=>{pointer=null;joystick={x:0,y:0};};stick.addEventListener('pointerup',release);stick.addEventListener('pointercancel',release);stick.addEventListener('lostpointercapture',release);
 addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();keys.add(e.key);}});addEventListener('keyup',e=>keys.delete(e.key));addEventListener('blur',()=>{keys.clear();release();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();release();}});
 addEventListener('resize',()=>{app.renderer.resize(innerWidth,innerHeight);view?.resize(innerWidth,innerHeight);hud?.reflow({width:innerWidth,height:innerHeight});panel?.reflow({width:innerWidth,height:innerHeight});pigPanel?.reflow({width:innerWidth,height:innerHeight});helperPanel?.reflow({width:innerWidth,height:innerHeight});missionPanel?.reflow({width:innerWidth,height:innerHeight});});
 (window as typeof window&{__catRaidLiveQA?:()=>ReturnType<typeof state>}).__catRaidLiveQA=state;
 let statusClock=0;app.ticker.add(()=>{const active=owner,dt=Math.min(.1,app.ticker.deltaMS/1000);
  if(active&&!paused&&!document.hidden){for(let i=0;i<rate;i++){active.advance(dt,{simulate:true,acceptInput:true,presentation:!eco,joystick:keys.size?{x:(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0),y:(keys.has('ArrowUp')?1:0)-(keys.has('ArrowDown')?1:0)}:joystick});if(active.closed)break;}updateHUD();hud?.update(dt);if(active.closed&&owner===active){discard();notice='已返回同一隔离测试档入口；普通场景没有启动。';updatePanel();}}
  statusClock+=dt;if(statusClock>.15){renderState();statusClock=0;}if(history.length>400)history.splice(0,history.length-400);
 });updatePanel();renderState();
}
